### ISSUE TITLE
Confusing AMD error message

### ISSUE THREAD

**Issue by NervosaX** [systemjs/builder#110]
Apparently I've had a double up of an import in my AMD define function, and I get a rather confusing error message because of it. My project is a project that I'm converting from requirejs to systemjs. Requirejs seems to allow double imports, where systemjs does not (and rightfully so.)

That minimum reproduction steps are as follow:

foo.js
```javascript
define([
  "foo",
  "foo"
], function() {});
```

```jspm bundle foo bar.js```

This responds with the error message as follows:

```
     Building the bundle tree for foo...

err  AssertionError: Error loading "foo" at file:/tmp/foo.js
     not already a dependency
         at Console.assert (console.js:102:23)
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1582:21
         at tryCatchReject (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at Pending.run (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
         at Scheduler._drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
         at Scheduler.drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:62:9)
         at process._tickCallback (node.js:415:13)

```

This error message is so vague that I had no idea what was going on.

**Comment by NervosaX** [comment]
Actually, looking at the stack trace there, perhaps this is an es6-module-loader issue?

**Comment by guybedford** [comment]
The dependencies are supposed to be deduped internally by code like https://github.com/systemjs/systemjs/blob/master/lib/extension-register.js#L536.

The only way I can think that is being skipped is if these are named AMD files already? A test case would be useful to fix this as the intention isn't to throw in these cases.

**Comment by NervosaX** [comment]
https://github.com/NervosaX/systemjs-dep-example

Here's a basic example using the systemjs builder trace. Removing the duplicate allows a working test case.

What is interesting is if you remove bar.js and baz.js, it doesn't throw any errors about the file not existing, but rather the error in my opening issue post.

**Comment by guybedford** [comment]
Great thanks, I've fixed this in https://github.com/systemjs/builder/commit/27c3b94a04985f75b166f2925560bfecf22ff94d.
