### ISSUE TITLE
Plugin not being transpiled

### ISSUE THREAD

**Issue by frankwallis** [systemjs/builder#119]
I have been trying to use systemjs-builder to bundle the typescript with plugin-typescript but I am getting an error [Unexpected reserved word] when trying to load the plugin. This indicates that plugin-typescript is not getting transpiled by traceur.

I have tried updating plugin-typescript to explicitly set its format to 'es6' and that changes the error but it is still not getting put through traceur. The strange thing is that I had it working at some point yesterday.

Can you think of anything I may be doing wrong? I have updated the example project in plugin-typescript to have a 'gulp bundle' task which exhibits the error.

**Comment by guybedford** [comment]
The issue is that setting `registry: 'npm'` in the package.json makes jspm think that the package is CommonJS.

I've added a new option called `jspmNodeConversion: false` which can be used alongside `registry: 'npm'` to ensure that this doesn't happen. It is coming in the next version of jspm to be posted very soon.

In the mean time I would suggest removing the `registry: 'npm'` part for now.

Just let me know if you need help further.

**Comment by frankwallis** [comment]
Thanks for the response - I've removed the 'registry: npm' setting and updated to systemjs-builder 0.10.0. I am still getting an error though. 

```
Cannot call method 'then' of undefined
    at Loader.pluginLoader.instantiate (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\lib\builder.js:57:6)
    at Promise.resolve.then.then.load.address (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1546:33)
    at tryCatchReject (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Fulfilled.when (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:930:4)
    at Pending.run (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Work\bitbucket\plugin-typescript\node_modules\systemjs-builder\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src.js:62:9)
    at process._tickCallback (node.js:419:13)
```

The error happens here:

```
  // 15.2.4.5
  function proceedToTranslate(loader, load, p) {
    p
    // 15.2.4.5.1 CallTranslate
    .then(function(source) {
      if (load.status != 'loading')
        return;

      return Promise.resolve(loader.loaderObj.translate({ name: load.name, metadata: load.metadata, address: load.address, source: source }))

      // 15.2.4.5.2 CallInstantiate
      .then(function(source) {
        load.source = source;
			console.log('here I am');
        return loader.loaderObj.instantiate({ name: load.name, metadata: load.metadata, address: load.address, source: source });
      })

      // 15.2.4.5.3 InstantiateSucceeded
      .then(function(instantiateResult) {
			
        if (instantiateResult === undefined) {
          load.address = load.address || '<Anonymous Module ' + ++anonCnt + '>';
```

So loader.loaderObj.instantiate is calling 'then' on an undefined.

```
Loader.prototype.instantiate = function(load) {
    // load transpiler as a global (avoiding System clobbering)
    if (load.name === this.transpiler) {
      var self = this;
      return {
        deps: [],
        execute: function() {
          var curSystem = g.System;
          var curLoader = g.Reflect.Loader;
          __eval('(function(require,exports,module){' + load.source + '})();', g, load);
          g.System = curSystem;
          g.Reflect.Loader = curLoader;
          return getTranspilerModule(self, load.name);
        }
      };
    }
// FW - added this
		else {
			return Promise.resolve(undefined);
		}
  };
```

Adding the condition at the end to return a valid promise allows everything to continue and the bundling now works fine. This is probably not the right fix but it keeps me going for now.

As before you can recreate this by running ```gulp bundle``` in plugin-typescript (after running jspm install in the example folder). Thanks.

**Comment by guybedford** [comment]
Great to hear that - thanks, I added a fix in https://github.com/systemjs/builder/commit/6d277bd7e94f827c8dc5f0844bd2e912913a98b6.
