### ISSUE TITLE
upgrading from jspm@0.16.0-beta to jspm@0.16.0-beta.3 broke something

### ISSUE THREAD

**Issue by davis** [systemjs/builder#210]
when doing a `jspm bundle-sfx src/main dist/bundle.js --minify --skip-source-maps`
i now run into the following error:

```
err  AssertionError: missing path
         at Module.require (module.js:363:3)
         at require (module.js:384:17)
         at /Users/manju/workspace/searcher-fe/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:157:16
         at Array.forEach (native)
         at wrapSFXOutputs (/Users/manju/workspace/searcher-fe/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:156:26)
         at /Users/manju/workspace/searcher-fe/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:136:14
         at lib$rsvp$$internal$$tryCatch (/Users/manju/workspace/searcher-fe/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/manju/workspace/searcher-fe/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/manju/workspace/searcher-fe/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/manju/workspace/searcher-fe/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
```

**Comment by guybedford** [comment]
If you put a console.log log in `systemjs-builder/lib/compile.js:157` logging the `format`, you should see a non-standard module format being used. We can throw a better error here though.

**Comment by guybedford** [comment]
I've added this commit which may give a more useful error message as well - https://github.com/systemjs/builder/commit/ad668f7607d0d539e63dca8b47f6946fe8391b80.

**Comment by davis** [comment]
thanks!! (and yeah that makes sense, i am using a module that worked for 0.16.0)
