### ISSUE TITLE
0.16.0 beta 3: Missing paths when jspm.js bundle-sfx ....

### ISSUE THREAD

**Issue by mysim1** [systemjs/builder#212]
When bundling I'm encountering a Missing paths error. 
```
err  AssertionError: missing path
         at Module.require (module.js:363:3)
         at require (module.js:384:17)
         at /Users/mysim1/Development/Products/Bizmark/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:157:16
         at Array.forEach (native)
         at wrapSFXOutputs (/Users/mysim1/Development/Products/Bizmark/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:156:26)
         at /Users/mysim1/Development/Products/Bizmark/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:136:14
         at lib$rsvp$$internal$$tryCatch (/Users/mysim1/Development/Products/Bizmark/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/mysim1/Development/Products/Bizmark/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/mysim1/Development/Products/Bizmark/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/mysim1/Development/Products/Bizmark/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
```

I've debugged the jspm build proces and found that the compiler list contains:
```
amd = true
cjs = true
defined = true
esm = true
```

Line 155 - 163 runs through a compilerMap which doesn't contain the ```defined``` entry.
```
// include compiler helpers at the beginning of outputs
  Object.keys(compilers).forEach(function(format) {
    compiler = require(compilerMap[format]);
    if (compiler.sfx)  {
      var sfx = compiler.sfx(loader);
      if (sfx)
        outputs.unshift(sfx);
    }
  });
```

So. Therefore this statement: 
```compiler = require(compilerMap[format]);```
**Fails**

**Comment by guybedford** [comment]
@mysim1 a fix for this has been added in https://github.com/systemjs/builder/commit/ad668f7607d0d539e63dca8b47f6946fe8391b80. Release will follow soon.

**Comment by guybedford** [comment]
Do let me know if you are still getting any of these build issues.
