### ISSUE TITLE
can't override baseURL

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#224]
trying to get build working again with latest stuff...

jspm 16.b3
builder 12

I can't seem to override baseURL anymore, even though this is an example in the builder/README! =(

```
[11:20:37] TypeError: baseURL should only be configured once and must be configured first.
  at SystemJSNodeLoader.SystemJSLoader.config (/Users/jon/checkout/gearlaunch/hub/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1388:13)
  at Builder.config (/Users/jon/checkout/gearlaunch/hub/node_modules/systemjs-builder/lib/builder.js:213:10)
  at /Users/jon/checkout/gearlaunch/hub/gulpfile.babel.js:165:11
  at lib$rsvp$$internal$$tryCatch (/Users/jon/checkout/gearlaunch/hub/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/jon/checkout/gearlaunch/hub/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/Users/jon/checkout/gearlaunch/hub/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/Users/jon/checkout/gearlaunch/hub/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)
```

config.js:

```
System.config({
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "github:*": "../../jspm_packages/github/*",
    "npm:*": "../../jspm_packages/npm/*"
  }
});
```

```
let bundler = (app) => {
	let builder = new Builder();

	return builder.loadConfig('src/main/config.js').then(function() {
		builder.config(
			{
				baseURL: 'file:' + process.cwd() + '/target',
				paths: {
					'github:*': '../jspm_packages/github/*.js',
					'npm:*': '../jspm_packages/npm/*.js'
				}
			}
		);
		return builder.buildSFX('js/' + app + '/app', path.war + '/js/' + app + '/' + app + '-bundle.js', {minify: false, sourceMaps: false});
	});
}
```

**Comment by nathanboktae** [comment]
I also saw this issue. Turns out you can bypass this assertion via this hacky method:

```
var Builder = require('systemjs-builder')
var builder = new Builder('./')

var baseURL = builder.loader.baseURL

builder.loadConfig('system.config.js')
  .then(function() {
    builder.loader.baseURL = baseURL
    // .... builder.build ....
  })
```

This assert seems unnecessary.

**Comment by guybedford** [comment]
For jspm it is advisable to do:

```javascript
var Builder = require('jspm').Builder;

// ...
```

It will then come with all the correct config.

**Comment by lookfirst** [comment]
closing, moving discussion to https://github.com/systemjs/builder/issues/225

**Comment by rolaveric** [comment]
The `var Builder = require('jspm').Builder;` hint should get added to the readme for JSPM users.

**Comment by guybedford** [comment]
@rolaveric this is documented at https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.
