### ISSUE TITLE
Fails to bundle when there are Flow `import type` statements

### ISSUE THREAD

**Issue by tengyifei** [systemjs/builder#231]
See https://github.com/babel/babel/issues/1996

To reproduce:
```bash
> jspm init
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesnt exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use an ES6 transpiler? [yes]:
Which ES6 transpiler would you like to use, Traceur, Babel or TypeScript?
(TypeScript does not yet have bundling support in jspm) [traceur]:Babel
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...
       system.js
       system-csp-production.js
       system.js.map
       system.src.js
       system-polyfills.js
       system-csp-production.js.map
       system-polyfills.src.js
       system-csp-production.src.js
       system-polyfills.js.map
     
     Using loader versions:
       systemjs@0.18.4
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Updating registry cache...
ok   Installed babel as npm:babel-core@^5.6.4 (5.6.20)
     Looking up github:jspm/nodelibs-process
     Looking up github:jspm/nodelibs-fs
     Looking up github:systemjs/plugin-json
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.1)
     Looking up npm:process
ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)
ok   Installed github:systemjs/plugin-json@^0.1.0 (0.1.0)
ok   Installed npm:process@^0.10.0 (0.10.1)
ok   Installed babel-runtime as npm:babel-runtime@^5.6.4 (5.6.20)
ok   Installed core-js as npm:core-js@^0.9.17 (0.9.18)
ok   Loader files downloaded successfully

> echo "import type { Foo } from './Foo.js';" > app.js
> echo "export class Foo { }" > Foo.js
> jspm bundle app.js
Building the bundle tree for app.js...
       app.js
     
err  TypeError: file:///Users/yifei/dev/1996test/app.js: Cannot read property 'toLowerCase' of undefined
         at check (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:22283:21)
         at NodePath.ModuleDeclaration (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:22312:5)
         at NodePath.call (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:23019:28)
         at NodePath.visit (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:23052:8)
         at TraversalContext.visitMultiple (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:22424:16)
         at TraversalContext.visit (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:22462:19)
         at Function.traverse.node (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:22579:17)
         at NodePath.visit (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:23069:26)
         at TraversalContext.visitSingle (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:22448:12)
         at TraversalContext.visit (file:///Users/yifei/dev/1996test/jspm_packages/npm/babel-core@5.6.20/browser.js:22464:19)
```

**Comment by guybedford** [comment]
I've pushed an experimental fix in https://github.com/systemjs/builder/commit/2b919dce51a7c54bb76a073aaa2c7956bb4910b0. It needs to run against jspm 0.16 beta, but let me know if you're able to test that out.

**Comment by tengyifei** [comment]
Yes it worked!

**Comment by guybedford** [comment]
Great, thanks for following up.

**Comment by davis** [comment]
@tengyifei  how are you using systemjs with flow?
