### ISSUE TITLE
Depcache?

### ISSUE THREAD

**Issue by zellwk** [systemjs/builder#248]
Is it possible to create a depcache with Systemjs builder? If so, how should I go about doing it?

**Comment by guybedford** [comment]
There is actually a `builder.getDepCache` function which is currently undocumented. It takes as input the traced tree for a build.

**Comment by zellwk** [comment]
What do you mean by "it takes as input the traced tree for a build"? How should I use `builder.getDepCache`? 

Kinda new to all of these. Thanks for the patience man

**Comment by guybedford** [comment]
I believe it should work with:

```javascript
buillder.trace('app').then(function(trace) {
  builder.getDepCache(trace.tree);
});
```

**Comment by zellwk** [comment]
I'm getting this error no matter what folder I give to 'app' 
~~~
[Error: EISDIR, read]
~~~

**Comment by guybedford** [comment]
Yes, you need to trace a module, not a folder.

**Comment by guybedford** [comment]
(note this will have a nicer error message stack coming in the next release)

**Comment by zellwk** [comment]
I'm sorry I don't understand. What do you mean by tracing a module?

**Comment by guybedford** [comment]
Reference a module path that is a file not a folder.

**Comment by zellwk** [comment]
What's a module here? Like `app.js`?

**Comment by guybedford** [comment]
Any SystemJS module that would load through SystemJS `System.import`.

**Comment by zellwk** [comment]
Is this correct? 

if I have this: 
```
  <script src="/jspm_packages/system.js"></script>
  <script src="/jspm.config.js"></script>
  <script>
    System.import('js/main');
  </script>
```

Then, I should writing this for depcache: 

```
 builder.trace('js/main').then(function(trace) {
    builder.getDepCache(trace.tree);
  }).catch((err)=> {
    console.log(err);
  });
```

However, when I ran this code, I get an undefined error: 

```
[TypeError: Can't call method on  undefined]
```

**Comment by guybedford** [comment]
Is the error being thrown during the trace or the `getDepCache` call above? Also if you log the `err.stack` that would also be much more useful to know the line numbers.

**Comment by zellwk** [comment]
The error is thrown during the `getDepCache` call. 

Here's the entire stack trace: 

```
ypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/babel-core/node_modules/core-js/modules/$.defined.js:3:63)
    at module.exports (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/babel-core/node_modules/core-js/modules/$.to-object.js:4:17)
    at keys (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/babel-core/node_modules/core-js/modules/es6.object.keys.js:6:18)
    at Function.keys (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/jspm/node_modules/traceur/bin/traceur.js:231:31)
    at Builder.getDepCache (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:362:10)
    at /Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/gulp/tasks/jspm.js:69:13
    at lib$rsvp$$internal$$tryCatch (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
[BABEL] file:/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js: Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default
```

**Comment by guybedford** [comment]
@zellwk it sounds like some interaction on `Object.keys` with Traceur runtime and core-js. Instead of calling getDepCache, see if you're able to use `Object.keys` at all in the environment at that line of code?

**Comment by zellwk** [comment]
Here's what I did: 

```
  builder.trace('./src/js/main').then(function(trace) {
    // builder.getDepCache(trace.tree);
    console.log(Object.keys.toString());
  }).catch((err)=> {
    console.log(err.stack);
  });
```

And here's what I got in the console: 

```
function keys(object) {
      return removeSymbolKeys($keys(object));
    }
```

**Comment by guybedford** [comment]
Note how that is no longer native code - so another dependency in your environment is overwriting `Object.keys`.

**Comment by zellwk** [comment]
Interesting. What's the native code for `Object.keys`? I'm using Gulp with this build right now, and I've tried logging `Object.keys` everywhere. Everything returns the same function. 

Is there anyway we can fix this?

**Comment by guybedford** [comment]
depCache is being deprecated for a straightforward call of `Object.keys(trace.tree)`.
