### ISSUE TITLE
Sudden bundling failure (was working fine before)

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#263]
All of the sudden after cleaning out node_modules and jspm_packages, my builder bundling is failing with this obscure failure...

```
[14:27:42] 'bundle-sell' errored after 1.89 s
[14:27:42] Error: TypeError: file:///Users/jon/checkout/gearlaunch/hub/target/jspm_packages/github/components/jquery@2.1.4/jquery.js:892
	var div = document.createElement("div");
	                  ^
Cannot read property 'createElement' of undefined
	Evaluating file:///Users/jon/checkout/gearlaunch/hub/target/jspm_packages/github/components/jquery@2.1.4/jquery.js
	Error loading file:///Users/jon/checkout/gearlaunch/hub/target/jspm_packages/github/components/jquery@2.1.4/jquery.js as "github:components/jquery@2.1.4/jquery" from file:///Users/jon/checkout/gearlaunch/hub/target/jspm_packages/github/components/jquery@2.1.4.js
  at formatError (/Users/jon/checkout/gearlaunch/hub/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/Users/jon/checkout/gearlaunch/hub/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:129:20)
  at Gulp.Orchestrator._emitTaskDone (/Users/jon/checkout/gearlaunch/hub/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/jon/checkout/gearlaunch/hub/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/jon/checkout/gearlaunch/hub/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at /Users/jon/checkout/gearlaunch/hub/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
  at lib$rsvp$$internal$$tryCatch (/Users/jon/checkout/gearlaunch/hub/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/jon/checkout/gearlaunch/hub/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/jon/checkout/gearlaunch/hub/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$$internal$$publishRejection (/Users/jon/checkout/gearlaunch/hub/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:419:7)
  at lib$rsvp$asap$$flush (/Users/jon/checkout/gearlaunch/hub/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
  at process._tickCallback (node.js:355:11)
```

In my gulpfile I have:

```
import {Builder} from 'jspm';

let bundler = (app) => {
	let builder = new Builder();
	return builder.buildSFX(`js/${app}/app`, `${path.war}/js/${app}/${app}-bundle.js`,
		{minify: situation.isProduction() || situation.isDemo(), sourceMaps: false});
};
```

```
jspm --version
0.16.0-beta.3
```

**Comment by lookfirst** [comment]
@guybedford https://github.com/lookfirst/broken2

```
npm install
gulp
```

**Comment by guybedford** [comment]
Thanks so much, fixed in https://github.com/systemjs/systemjs/commit/4524c2e71eea0f8eb35ee786aacfa91bf778181a.
