### ISSUE TITLE
build:false causing systemjs error

### ISSUE THREAD

**Issue by drieks** [systemjs/builder#326]
Running this file:
index.js
```
var Builder = require("systemjs-builder");
var builder = new Builder({
    meta: {
        "testImport": {
            build: false
        }
    }
});

builder.bundle("testSource.js").then(function (result) {
    console.log(result);
});
```

Will create this output:
```
System.registerDynamic("testSource.js", ["testImport"], true, function(require, exports, module) {
  ;
  var global = this,
      __define = global.define;
  global.define = undefined;
  require("testImport");
  global.define = __define;
  return module.exports;
});
```
However when loading this file using System.import() an Exception is thrown:
```
TypeError: Cannot read property 'lastIndexOf' of undefined
    at SystemJSLoader.booleanConditional (http://localhost:8080/bower_components/system.js/dist/system.src.js:4134:28)
    at SystemJSLoader.alias [as normalize] (http://localhost:8080/bower_components/system.js/dist/system.src.js:4171:33)
    at SystemJSLoader.esmRegEx (http://localhost:8080/bower_components/system.js/dist/system.src.js:3066:55)
    at SystemJSLoader.loader (http://localhost:8080/bower_components/system.js/dist/system.src.js:3283:24)
    at SystemJSLoader.loader (http://localhost:8080/bower_components/system.js/dist/system.src.js:3510:26)
    at SystemJSLoader.loader (http://localhost:8080/bower_components/system.js/dist/system.src.js:3809:26)
    at SystemJSLoader.negation [as instantiate] (http://localhost:8080/bower_components/system.js/dist/system.src.js:4023:28)
    at http://localhost:8080/bower_components/system.js/dist/system.src.js:346:33
```

**Comment by guybedford** [comment]
Can you insert a `console.log(entry)` at line 3064 and let me know the output?

**Comment by drieks** [comment]
Hello, I'm sorry but it seems that the real cause for this was that I used System.define and not System.register.

Maybe this could log a warning? Nevertheless everything is working now for me, thank you!
