### ISSUE TITLE
Invalidate API does not invalidate files

### ISSUE THREAD

**Issue by OrKoN** [systemjs/builder#353]
I have encountered the following problem: https://github.com/jackfranklin/jspm-dev-builder/issues/3#issuecomment-147658392

I have debugged what happens during invalidation using this test project https://github.com/OrKoN/jspm-dev-builder/tree/master/test-project:

![selection_168](https://cloud.githubusercontent.com/assets/399150/10481610/ef2d2fac-7271-11e5-8197-40eb208ee0ad.png)

*`invalidationModuleName` equals `main.js`*.

It looks like `this.cache.trace` is an object w/o keys so nothing is invalidated. The subsequent calls to `bundle` the expression triggers re-build of entire app.

**Comment by guybedford** [comment]
It looks like the build function in dev builder will create a new builder instance - https://github.com/jackfranklin/jspm-dev-builder/blob/master/index.js#L38. This will obviously lose the cache.

**Comment by OrKoN** [comment]
Thanks @guybedford

**Comment by OrKoN** [comment]
@guybedford @jackfranklin

I have found another problem. Somehow incremental builds work in the jspm-dev-builder project but not in my app - whenever I change main.js the bundle is rebuilt with the old contents of main.js. I traced it down to `lib/trace.js`:

```
  if (this.tracing[canonical])
    return this.tracing[canonical];
```

on rebuild, the old source is still being found in `this.tracing`.  I tried to fix it by invalidating cache like this:

```
  var cache = this.getCache();
  Object.keys(cache.trace).forEach(function(canonical) {
    var moduleName = loader.normalizeSync(canonical);
    if (matchesInvalidation(moduleName)) {
      invalidated.push(moduleName);
      cache.trace[canonical] = undefined;
    }
  });
  this.setCache(cache);
```

So that tracer.tracing is destroyed by setCache. But that didn't work either - now main.js has no source on re-builds. I assume that something else depends on this tracing object but I cannot figure out what exactly.

**Comment by guybedford** [comment]
@OrKoN thanks for the detailed analysis as always. I've added a fix in https://github.com/systemjs/builder/commit/a96fa363edf10fa455bccf94dac9cd5841aa52eb, just let me know if you notice anything further at all.

**Comment by OrKoN** [comment]
@guybedford I still have the same problem as after the fix I applied myself: the module that is being invalidated becomes empty. For example, `System.register("mappings.js", [], function() { return { setters: [], execute: function() {} } });` I have edited `mappings.js`, saved and got the following builder output:

```
jspm-dev-builder Invalidated mappings.js from cache
jspm-dev-builder jspm build starting main.js
jspm-dev-builder Building non-SFX bundle
builder.build is deprecated. Using builder.bundle instead.
jspm-dev-builder jspm build finished 332
```

Here is my gulp task: 

```
gulp.task('watch', function(done) {
  var browserSync = require('browser-sync');
  var DevBuilder = require('jspm-dev-builder');
  var reload = browserSync.reload;
  var path = require('path');
  var baseURL = new jspm.Builder().loader.baseURL.replace('file://', '');

  var appDevBuilder = new DevBuilder({
    jspm: require('jspm'), // so you can use your local version of jspm
    expression: path.join('main.js'), // path to your app's entry point
    outLoc: path.join('app', 'app-bundle.js'), // where you want the output file
    logPrefix: 'jspm-dev-builder', // put at the beginning of log messages from dev builder
    buildOptions: {
      minify: false,
      mangle: false,
      sourceMaps: false
    }
  });

  appDevBuilder.build().then(function() {
    done();
    browserSync({
      online: false,
      open: false,
      server: {
        baseDir: ['app-data', 'app', 'dist']
      }
    });

    gulp.watch([
      'app/*.html',
      'app-data/css/**/*.css',
      'app-data/imgs/**/*'
    ], function(file) {
      reload(file.path);
    });

    gulp.watch([
      'app/**/*.js',
      'app/**/*.hbs',
    ], function(file) {
      var moduleId = path.relative(baseURL, file.path);
      if (moduleId !== 'app-bundle.js') {
        appDevBuilder.build(moduleId);
      }
    });
  });
});
```

Maybe I am doing something wrong? I can't spot the problem. 

The simpler test project in jspm-dev-builder still works fine.

**Comment by guybedford** [comment]
@OrKoN this should definitely work ok. Are you sure the right change of SystemJS Builder is applying. To investigate further, could you send the contents of `JSON.stringify(appDevBuilder.cache)` immediately after invalidation?

**Comment by OrKoN** [comment]
@guybedford the systemjs-builder version is 0.14.9. The output `JSON.stringify(appDevBuilder.cache)` is huge. What exactly should I check? I have captured trace and load state for mappings.js:

```
Load for mappings.js = 
{
  "hash": "599f817c6d3ff483fde0de18ac97a933",
  "output": {
    "source": "System.register('mappings.js', ['application/application.js', 'index/index.js', 'event/event.js', 'event/event-list.js', 'event/event-add.js', 'event-day/event-day.js', 'event-slot/event-slot.js', 'event-table/event-table.js', 'event-table/event-table-row.js', 'address/address.js', 'payment/payment.js', 'cart/cart.js', 'event-reservation/event-reservation.js', 'cron_service/cron_service.js', 'job_service/job_service.js', 'event-specifications/event-specification-list.js', 'event-specifications/event-specification.js', 'vouchers/voucher-list-item.js', 'vouchers/voucher-add.js', 'vouchers/voucher.js', 'invoices/invoice-list-item.js', 'invoices/invoice.js', 'orders/order-list-item.js', 'orders/order.js', 'components/status-operation-toolbar.js'], function (_export) {\n  'use strict';\n\n  // single event\n\n  // event list\n\n  // event add\n\n  // event day component for agenda in list\n\n  // other components\n\n  // management\n\n  // overwrites\n\n  // components\n\n  return {\n    setters: [function (_applicationApplicationJs) {\n      for (var _key in _applicationApplicationJs) {\n        if (_key !== 'default') _export(_key, _applicationApplicationJs[_key]);\n      }\n    }, function (_indexIndexJs) {\n      for (var _key2 in _indexIndexJs) {\n        if (_key2 !== 'default') _export(_key2, _indexIndexJs[_key2]);\n      }\n    }, function (_eventEventJs) {\n      for (var _key3 in _eventEventJs) {\n        if (_key3 !== 'default') _export(_key3, _eventEventJs[_key3]);\n      }\n    }, function (_eventEventListJs) {\n      for (var _key4 in _eventEventListJs) {\n        if (_key4 !== 'default') _export(_key4, _eventEventListJs[_key4]);\n      }\n    }, function (_eventEventAddJs) {\n      for (var _key5 in _eventEventAddJs) {\n        if (_key5 !== 'default') _export(_key5, _eventEventAddJs[_key5]);\n      }\n    }, function (_eventDayEventDayJs) {\n      for (var _key6 in _eventDayEventDayJs) {\n        if (_key6 !== 'default') _export(_key6, _eventDayEventDayJs[_key6]);\n      }\n    }, function (_eventSlotEventSlotJs) {\n      for (var _key7 in _eventSlotEventSlotJs) {\n        if (_key7 !== 'default') _export(_key7, _eventSlotEventSlotJs[_key7]);\n      }\n    }, function (_eventTableEventTableJs) {\n      for (var _key8 in _eventTableEventTableJs) {\n        if (_key8 !== 'default') _export(_key8, _eventTableEventTableJs[_key8]);\n      }\n    }, function (_eventTableEventTableRowJs) {\n      for (var _key9 in _eventTableEventTableRowJs) {\n        if (_key9 !== 'default') _export(_key9, _eventTableEventTableRowJs[_key9]);\n      }\n    }, function (_addressAddressJs) {\n      for (var _key10 in _addressAddressJs) {\n        if (_key10 !== 'default') _export(_key10, _addressAddressJs[_key10]);\n      }\n    }, function (_paymentPaymentJs) {\n      for (var _key11 in _paymentPaymentJs) {\n        if (_key11 !== 'default') _export(_key11, _paymentPaymentJs[_key11]);\n      }\n    }, function (_cartCartJs) {\n      for (var _key12 in _cartCartJs) {\n        if (_key12 !== 'default') _export(_key12, _cartCartJs[_key12]);\n      }\n    }, function (_eventReservationEventReservationJs) {\n      for (var _key13 in _eventReservationEventReservationJs) {\n        if (_key13 !== 'default') _export(_key13, _eventReservationEventReservationJs[_key13]);\n      }\n    }, function (_cron_serviceCron_serviceJs) {\n      for (var _key14 in _cron_serviceCron_serviceJs) {\n        if (_key14 !== 'default') _export(_key14, _cron_serviceCron_serviceJs[_key14]);\n      }\n    }, function (_job_serviceJob_serviceJs) {\n      for (var _key15 in _job_serviceJob_serviceJs) {\n        if (_key15 !== 'default') _export(_key15, _job_serviceJob_serviceJs[_key15]);\n      }\n    }, function (_eventSpecificationsEventSpecificationListJs) {\n      for (var _key16 in _eventSpecificationsEventSpecificationListJs) {\n        if (_key16 !== 'default') _export(_key16, _eventSpecificationsEventSpecificationListJs[_key16]);\n      }\n    }, function (_eventSpecificationsEventSpecificationJs) {\n      for (var _key17 in _eventSpecificationsEventSpecificationJs) {\n        if (_key17 !== 'default') _export(_key17, _eventSpecificationsEventSpecificationJs[_key17]);\n      }\n    }, function (_vouchersVoucherListItemJs) {\n      for (var _key18 in _vouchersVoucherListItemJs) {\n        if (_key18 !== 'default') _export(_key18, _vouchersVoucherListItemJs[_key18]);\n      }\n    }, function (_vouchersVoucherAddJs) {\n      for (var _key19 in _vouchersVoucherAddJs) {\n        if (_key19 !== 'default') _export(_key19, _vouchersVoucherAddJs[_key19]);\n      }\n    }, function (_vouchersVoucherJs) {\n      for (var _key20 in _vouchersVoucherJs) {\n        if (_key20 !== 'default') _export(_key20, _vouchersVoucherJs[_key20]);\n      }\n    }, function (_invoicesInvoiceListItemJs) {\n      for (var _key21 in _invoicesInvoiceListItemJs) {\n        if (_key21 !== 'default') _export(_key21, _invoicesInvoiceListItemJs[_key21]);\n      }\n    }, function (_invoicesInvoiceJs) {\n      for (var _key22 in _invoicesInvoiceJs) {\n        if (_key22 !== 'default') _export(_key22, _invoicesInvoiceJs[_key22]);\n      }\n    }, function (_ordersOrderListItemJs) {\n      for (var _key23 in _ordersOrderListItemJs) {\n        if (_key23 !== 'default') _export(_key23, _ordersOrderListItemJs[_key23]);\n      }\n    }, function (_ordersOrderJs) {\n      for (var _key24 in _ordersOrderJs) {\n        if (_key24 !== 'default') _export(_key24, _ordersOrderJs[_key24]);\n      }\n    }, function (_componentsStatusOperationToolbarJs) {\n      for (var _key25 in _componentsStatusOperationToolbarJs) {\n        if (_key25 !== 'default') _export(_key25, _componentsStatusOperationToolbarJs[_key25]);\n      }\n    }],\n    execute: function () {}\n  };\n});\n//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJtYXBwaW5ncy5qcyIsInNvdXJjZXNDb250ZW50IjpbXX0=",
    "sourceMap": null
  }
}
Trace for mappings.js = 
undefined

```

**Comment by guybedford** [comment]
@OrKoN after re-running the load, is the trace cache then correctly populated again?

**Comment by sgwatgit** [comment]
Hey guys,

I'm running into this same issue using the jspm-dev-builder.

After running the bundle the 2nd time through, the file I changed disappears from my bundle.

```
gulp.task('build-watch', [], function () {
	let appBuilder = new DevBuilder({
		jspm: jspm, // so you can use your local version of jspm
		expression: [app/**/*.js], // path to your app's entry point
		outLoc: 'public/jsa.js', // where you want the output file
		logPrefix: 'jspm-app', // put at the beginning of log messages from dev builder
		buildOptions: bundleOptions
	});

	$.watch('src/js/app/**/*.js', function(vinyl) {
		// this is how you get the relative path from a vinyl file instance
		log(`Path: ${vinyl.path}`);
		log(`Cwd: ${vinyl.cwd}`);
		log(`Base: ${vinyl.base}`);
		log(`Relative: ${vinyl.relative}`);
		appBuilder.build(`src/js/app/${vinyl.relative}`)
			.then(function success(builder) {
                // this function performs DI annotation for angular (works fine)
				buildScripts.scriptsAnnotate();
				log("Finished annotation");
			});
	});
});
```

Running the watch looks like this in the console

```
$ gulp build-watch
[14:47:24] Using gulpfile C:\dev\demos\jspm-systemjs-angular-1x\gulpfile.js
[14:47:24] Starting 'build-watch'...
[14:47:25] Finished 'build-watch' after 1.48 s
[14:47:30] Path: C:\dev\demos\jspm-systemjs-angular-1x\src\js\app\jsa.module.js
[14:47:30] Cwd: C:\dev\demos\jspm-systemjs-angular-1x
[14:47:30] Base: C:\dev\demos\jspm-systemjs-angular-1x\src\js\app\
[14:47:30] Relative: jsa.module.js
jspm-app Invalidated src/js/app/jsa.module.js from cache
jspm-app jspm build starting [app/**/*.js]
jspm-app Building non-SFX bundle
builder.build is deprecated. Using builder.bundle instead.
jspm-app jspm build finished 1456
[14:47:31] Angular-annotating jsa.js in ./public/
[14:47:32] Finished annotation
```

The contents of my main app entry point `src/js/app/jsa.module.js` looks like this in my bundle after the second (cached) pass through the DevBuilder.build
```
System.register("app/jsa.module", [], function() { return { setters: [], execute: function() {} } });
```

But after the first build it looks like this
```
System.register('app/jsa.module', ['github:angular/bower-angular@1.4.7', 'github:angular-ui/ui-router@0.2.15', 'app/common/common.module', 'app/home/home.module', 'app/rep/rep.module', 'public/templates', 'styles/styles-adapter'], function (_export) {
	'use strict';

	var angular, uiRouter, commonModule, homeModule, repModule, templatesModule, styles, moduleName, appModule;

	function config($locationProvider) {
		"ngInject";
		console.log("ABCDEFG");
		$locationProvider.html5Mode(true).hashPrefix('!');
	}
	config.$inject = ['$locationProvider'];

	return {
		setters: [function (_githubAngularBowerAngular147) {
			angular = _githubAngularBowerAngular147['default'];
		}, function (_githubAngularUiUiRouter0215) {
			uiRouter = _githubAngularUiUiRouter0215['default'];
		}, function (_appCommonCommonModule) {
			commonModule = _appCommonCommonModule['default'];
		}, function (_appHomeHomeModule) {
			homeModule = _appHomeHomeModule['default'];
		}, function (_appRepRepModule) {
			repModule = _appRepRepModule['default'];
		}, function (_publicTemplates) {
			templatesModule = _publicTemplates['default'];
		}, function (_stylesStylesAdapter) {
			styles = _stylesStylesAdapter['default'];
		}],
		execute: function () {
			moduleName = "jsa";
			appModule = angular.module(moduleName, ['ui.router', commonModule.name, homeModule.name, repModule.name, 'jsa.templates']).config(config);
			angular.element(document).ready(function () {
				angular.bootstrap(document, [appModule.name], { strictDI: true });
			});
		}
	};
});
```

Note: There might be copy/paste typos in the code, but the output is the same

**Comment by sgwatgit** [comment]
I tried doing this process with cache & invalidation without `jspm-dev-builder`

```
gulp.task('build-watch', [], function () {
	let appCache = {};
	let builder = new Builder('/', './config.js');
	builder.setCache(appCache);
	
	$.watch('src/js/app/**/*.js', function(vinyl) {
		builder.invalidate(`app/${vinyl.relative}`);
		builder.bundle(
			config.app.module.app, 
			config.dir.public + config.file.bundle.app, 
			config.setting.bundleOptions,
			appCache)
			.then(function () {
				appCache = builder.getCache();
				log(`Completed bundle ${config.file.bundle.app} in ${config.dir.public}`);
			}).catch(function (err) {
				log(`Error : ${err}`);
			});
	});
});
```

I still end up with this at the end of my app bundle file right before the sourcemaps.
```
System.register("app/jsa.module", [], function() { return { setters: [], execute: function() {} } });
```
and there is no other `System.register("app/jsa.module", ...);` in the bundle.

**Comment by OrKoN** [comment]
> after re-running the load, is the trace cache then correctly populated again?

@guybedford  Sorry, I have missed your question. What does re-running the load mean? If I bundle anew, everything works as expected. But if I invalidate a file by its name, and then bundle using the same instance, the file gets registered as an empty module. So the source file is not read again after the re-validation. Btw, the jspm-dev-builder@0.1.0 still works fine for me.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/commit/a1c15201698dd7cf01813285767da2a2e178fd31.

**Comment by OrKoN** [comment]
Thanks! Do you think if it's a good idea to bring jspm-dev-builder functionality into jspm? `jspm.watch` that watches app files and invalidates/rebuilds would be super helpful in my opinion?

**Comment by iksose** [comment]
@OrKoN did the  patch fix your issue?

**Comment by OrKoN** [comment]
@iksose Haven't tried yet. I will give it a try on Monday

**Comment by OrKoN** [comment]
@iksose works for me

**Comment by OrKoN** [comment]
@guybedford @iksose I have tested the patch with loader plugins and found another problem:

```js

  test('Bundle example with plugins', function() {
    var builder = new Builder('test/output', 'test/output/config.js');
    fs.writeFileSync('./test/output/dynamic-module.hbs', 'TestString5');

    return builder.bundle('dynamic-module.hbs!')
      .then(function(output) {
        assert(output.source.match(/TestString5/), 'Initial build fails');

        builder.invalidate('dynamic-module.hbs');

        fs.writeFileSync('./test/output/dynamic-module.hbs', 'TestString6');

        return builder.bundle('dynamic-module.hbs!');
      })
      .then(function(output) {
        assert(output.source.match(/TestString6/), 'Subsequent build fails');
      })
      .catch(function(err) {
        throw err;
      });
  });jspm install hbs=github:n-fuse/plugin-ember-hbs@shim-free
```

```sh
~/builder$ ./node_modules/.bin/mocha -g 'Bundle example'


  Test compiler cache
    ✓ Bundle example (92ms)
Compiling template: file:///home/alex/builder/test/output/dynamic-module.hbs
    1) Bundle example with plugins


  1 passing (632ms)
  1 failing

  1) Test compiler cache Bundle example with plugins:
     AssertionError: Subsequent build fails
      at test/test-build-cache.js:147:9
      at lib$rsvp$$internal$$tryCatch (node_modules/rsvp/dist/rsvp.js:493:16)
      at lib$rsvp$$internal$$invokeCallback (node_modules/rsvp/dist/rsvp.js:505:17)
      at lib$rsvp$$internal$$publish (node_modules/rsvp/dist/rsvp.js:476:11)
      at lib$rsvp$asap$$flush (node_modules/rsvp/dist/rsvp.js:1198:9)

```

To install a hbs plugin I ran `jspm init` in `test/output`, installed hbs with `jspm install hbs=github:n-fuse/plugin-ember-hbs@shim-free` and then put `"ember": "@empty"` to the generated config.js. The test fails because the output of the second bundle call contains the stale `TestString5`

**Comment by guybedford** [comment]
@OrKoN thanks. Perhaps make sure to confirm that the `builder.invalidate` returns the correct list of invalidated modules here (and not an empty list). Then I will check this out when I can.

**Comment by OrKoN** [comment]
@guybedford console.log(builder.invalidate('dynamic-module.hbs')); returns `[]` but `console.log(builder.invalidate('dynamic-module.hbs!'));` works fine. What would be the right way to translate file path to the module name with `!`? is the JSPM API for this?

**Comment by guybedford** [comment]
@OrKoN no unfortunately not, you need to know it was called this way. This is another reason why it is better to use plugins via configuration over syntax.

**Comment by OrKoN** [comment]
I see. We still have not switched to the long-awaited feature of plugins via configuration. Totally makes sense.

**Comment by iksose** [comment]
@OrKoN what happens if you try to invalidate the same .js multiple times consecutively?

**Comment by OrKoN** [comment]
@iksose .js files work fine for me. Do you have any problems?

**Comment by iksose** [comment]
If I have, say, 5 files and I change any of them, with guy's patch, it works.

But if I change the same one twice in a row, it gives me an error `ENOENT for my/directory/24.js` where 24 is any random number. Might be jspm-dev-builder and not a jspm issue.

**Comment by OrKoN** [comment]
Is there a pause between changes?

**Comment by sgwatgit** [comment]
@iksose How did you patch the changes/fix into `jspm-dev-builder`? Did you modify your local jspm or the one in `jspm-dev-builder`?

@guybedford I see you marked this as pending release, but since these are fixes to systemjs-builder, when will the fix be pulled into a jspm release?

**Comment by iksose** [comment]
I just added the changes inline myself

**Comment by guybedford** [comment]
@iksose are you running an sfx bundle there specifically?

**Comment by iksose** [comment]
yes

**Comment by iksose** [comment]
Will it be supported for sfx?

**Comment by guybedford** [comment]
SFX support is not guaranteed currently, which sounds like the issue. Happy to work towards supporting that as well though.

**Comment by guybedford** [comment]
Released in 0.14.10.

**Comment by sgwatgit** [comment]
@guybedford Thanks for all the work on this! I just tested this with `jspm-dev-builder` and the issue https://github.com/jackfranklin/jspm-dev-builder/issues/7 appears to be resolved as long as I use my local updated `jspm`. With this fix I feel pretty good about having jspm/systemjs as part of my workflow.

**Comment by jackfranklin** [comment]
@sgwatgit perfect, I'll update jspm-dev-builder today with the latest jspm by default and that should be that :+1:
