### ISSUE TITLE
Build error (jspm bundle --minify throws Unexpected token error)

### ISSUE THREAD

**Issue by richburdon** [systemjs/builder#356]
Running:

    jspm bundle --minify app/demo/bootstrap src/main/javascript/min/demo.min.js

I get the exception below. Without "--minify" things are OK. I'm starting to strip down my app's dependencies to try to find the problem, but can anyone suggest an additional means of debugging this problem?

Thanks.

err  Error: Unexpected token: name (module) (line: 22887, col: 8, pos: 890965)

     Error
         at new JS_Parse_Error (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:196:18)
         at js_error (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:204:11)
         at croak (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:680:9)
         at token_error (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:688:9)
         at unexpected (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:694:9)
         at semicolon (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:714:43)
         at simple_statement (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:894:73)
         at /Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:767:19
         at /Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:727:24
         at block_ (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1007:20)
         at minify (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/systemjs-builder/lib/output.js:78:11)
         at exports.writeOutputs (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/systemjs-builder/lib/output.js:149:14)
         at /Users/nx/projects/src/demo/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:413:14
         at lib$rsvp$$internal$$tryCatch (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
         at lib$rsvp$$internal$$publish (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:476:11)
         at lib$rsvp$asap$$flush (/Users/nx/projects/src/demo/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
         at doNTCallback0 (node.js:417:9)
         at process._tickCallback (node.js:346:13)

**Comment by guybedford** [comment]
@richburdon perhaps try not using minification, then run uglify as a separate step to get the actual debug information?

**Comment by guybedford** [comment]
(by separate step I mean via https://github.com/mishoo/UglifyJS2)
