### ISSUE TITLE
Parallel builds under gulp throws error - 0.14.10 regression

### ISSUE THREAD

**Issue by majo44** [systemjs/builder#402]
Builder is throwing an error if we try to starts in parallel few builds . We are crating new Builder(); on each separated gulp task, so we are not share instance of builder. 

There was not such problem in 0.14.9

```
13-Nov-2015 17:36:19	Error: TypeError: baseURL should only be configured once and must be configured first.
13-Nov-2015 17:36:19	    at SystemJSNodeLoader.SystemJSLoader.config (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1642:13)
13-Nov-2015 17:36:19	    at SystemJSNodeLoader.loader.config (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/lib/builder.js:137:18)
13-Nov-2015 17:36:19	    at eval (eval at executeConfigFile (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/lib/builder.js:267:3), <anonymous>:7:8)
13-Nov-2015 17:36:19	    at Builder.executeConfigFile (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/lib/builder.js:267:35)
13-Nov-2015 17:36:19	    at lib$rsvp$$internal$$tryCatch (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:493:16)
13-Nov-2015 17:36:19	    at lib$rsvp$$internal$$invokeCallback (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:505:17)
13-Nov-2015 17:36:19	    at lib$rsvp$$internal$$publish (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:476:11)
13-Nov-2015 17:36:19	    at lib$rsvp$asap$$flush (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:1198:9)
13-Nov-2015 17:36:19	    at doNTCallback0 (node.js:419:9)
13-Nov-2015 17:36:19	    at process._tickCallback (node.js:348:13)
13-Nov-2015 17:36:19	    at /mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/lib/builder.js:27:9
13-Nov-2015 17:36:19	    at Object.lib$rsvp$events$$default.trigger (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:245:13)
13-Nov-2015 17:36:19	    at null._onTimeout (/mnt/BCC-WKUI24-CP/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:779:47)
13-Nov-2015 17:36:19	    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by fictitious** [comment]
Could you please try 0.14.11 - I have a test case with the same error for 0.14.10, and it works now for me - https://gist.github.com/fictitious/37bf4736f0492ec0f942

**Comment by majo44** [comment]
Yes, problem not occurs on  0.14.11
