### ISSUE TITLE
Minify is not working on a js that contains generators

### ISSUE THREAD

**Issue by togakangaroo** [systemjs/builder#472]
When I have a simple js file containing a generator I cannot minify

app.js:

```
function* foo() {
	console.log("woo")
	yield 123
}

foo();
```

with my config.js pretty standard:

```
System.config({
  baseURL: "/js",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
    "blacklist": [
    ]
  },
  ,,,
```

running the following without the `--minify` flag works fine. But with the flag...

```
PS W:\temp\js> jspm -v
0.16.23
Running against local jspm install.
PS W:\temp\js> jspm bundle app ../foo.js --minify
     Building the bundle tree for app...

       app.js


err  Error: Unexpected token: operator (*) (line: 5, col: 12, pos: 233)

     Error
         at new JS_Parse_Error (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1526:18)
         at js_error (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1534:11)
         at croak (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2025:9)
         at token_error (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2033:9)
         at unexpected (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2039:9)
         at function_ (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2308:13)
         at eval (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2160:24)
         at eval (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2072:24)
         at block_ (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2352:20)
         at eval (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2325:25)
         at function_ (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2330:15)
         at expr_atom (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2538:24)
         at maybe_unary (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2708:19)
         at expr_ops (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2743:24)
         at maybe_conditional (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2748:20)
         at maybe_assign (eval at <anonymous> (W:\temp\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2772:20)
         at minify (W:\temp\node_modules\systemjs-builder\lib\output.js:78:11)
         at exports.writeOutputs (W:\temp\node_modules\systemjs-builder\lib\output.js:148:14)
         at W:\temp\node_modules\systemjs-builder\lib\builder.js:536:14
         at tryCatcher (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:11:23)
         at Promise._settlePromiseFromHandler (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:489:31)
         at Promise._settlePromise (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:546:18)
         at Promise._settlePromise0 (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:591:10)
         at Promise._settlePromises (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:674:18)
         at Async._drainQueue (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:125:16)
         at Async._drainQueues (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:135:10)
         at Immediate.Async.drainQueues [as _onImmediate] (W:\temp\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:16:14)
         at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by guybedford** [comment]
If you know a good minifier (we're using UglifyJS) that can handle generators I'd be happy to upgrade to that.
