### ISSUE TITLE
builder.buildStatic === No resolution found at all for condition...

### ISSUE THREAD

**Issue by mnichols** [systemjs/builder#502]
Using builder@0.15.9 with jspm@beta latest like this:
```js
import path from 'path'
import Builder from 'systemjs-builder'

// is this the right way to load the configs i use for jspm 0.17 beta?
const builder = new Builder(__dirname,'./jspm.browser.js')
builder.loadConfig('./jspm.config.js')
.then(() => {
    builder.buildStatic('./app/tests/async-spec.js','./built.js', {format: 'esm'})
})
```

I am getting this error and stack when I try to `buildStatic`:
```
Unhandled rejection TypeError: No resolution found at all for condition circleup-circle/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/jspm_packages/github/jspm/nodelibs-process@0.2.0-alpha/#:./process.js.
    at /Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/systemjs-builder/lib/trace.js:637:15
    at Array.forEach (native)
    at /Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/systemjs-builder/lib/trace.js:630:6
    at tryCatcher (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mnichols/dev/circleup/CircleUp-Main-Site/circle/static/circle/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Yet this works when i run `builder.bundle('./app/tests/async-spec.js','./built.js', {format: 'esm'})`**

- This happens regardless of the module format I choose. 
- I verified that the path to `jspm_packages/github/jspm/nodelibs-process@0.2.0-alpha/process.js` exists
- this script is running at the top level of my app

I am new to systemjs bundling and I am not sure how to back into solving this. Is my configuration loading correct for use with jspm@beta ? What am I doing wrong to get a static build?

**Comment by guybedford** [comment]
Static builds need to be made for an exact environment - the browser or Node. So try setting `browser: true` or `node: true` accordingly in the build options.

**Comment by mnichols** [comment]
You are **da bomb**. That fixed me up!. I looked on docs for that but I can't find that requirement anywhere stated. Is there another place than the README.md to be looking?
