### ISSUE TITLE
Mangling issue with common dependencies

### ISSUE THREAD

**Issue by rpkilby** [systemjs/builder#521]
Our app currently contains two main packages `app` and `api`. We're trying to build three bundles: 3rd party dependencies, the app, and the api. 
```sh
$ jspm bundle "api/**/* + app/**/* - [api/**/*] - [app/**/*]" deps.bundle.min.js --minify
$ jspm bundle "api/**/* - deps.bundle.min.js" api.bundle.min.js --minify
$ jspm bundle "app/**/* - api.bundle.min.js - deps.bundle.min.js" app.bundle.min.js --minify
```

The above fails when creating either the second or third bundles - they have the same traceback:
```
Error tracing deps.bundle.min.js at file:///<project>/deps.bundle.min.js
  Error: Unable to calculate canonical name to bundle file:///<project>/env. Ensure that this module sits within the baseURL or a wildcard path config.
    at getCanonicalNamePlain (/<project>/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:215:13)
    at getCanonicalName (/<project>/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:142:19)
    at /<project>/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:443:36
    at tryCatchReject (/<project>/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:1183:30)
    at runContinuation1 (/<project>/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:1142:4)
    at Fulfilled.when (/<project>/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:930:4)
    at Pending.run (/<project>/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:821:13)
    at Scheduler._drain (/<project>/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:97:19)
    at Scheduler.drain (/<project>/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:62:9)
    at process._tickCallback (node.js:419:13)
```

However, this works:
```sh
$ jspm bundle "api/**/* - [api/**/*]" api.deps.bundle.min.js --minify
$ jspm bundle "api/**/* - api.deps.bundle.min.js" api.bundle.min.js --minify

$ jspm bundle "app/**/* - [app/**/*]" app.deps.bundle.min.js --minify
$ jspm bundle "app/**/* - app.deps.bundle.min.js" app.bundle.min.js --minify
```

Adding `--no-mangle` to the first bundle also works:
```sh
$ jspm bundle "api/**/* + app/**/* - [api/**/*] - [app/**/*]" deps.bundle.min.js --minify --no-mangle
$ jspm bundle "api/**/* - deps.bundle.min.js" api.bundle.min.js --minify
$ jspm bundle "app/**/* - api.bundle.min.js - deps.bundle.min.js" app.bundle.min.js --minify
```

It doesn't look like a mangling issue with one of the dependencies, as the respective packages dependencies can be built. Maybe there's some interaction with mangling and the arithmetic?

**Comment by guybedford** [comment]
Can you share a link to the minified output of `deps.bundle.min.js` by any chance? Or at least a minimal version of it with code removed that breaks as well.

The issue is in detecting that the file is a bundle and not a module that should be traced normally, which would be good to catch exactly how that is happening.

**Comment by rpkilby** [comment]
I'll try to work on a minimal reproduction of this later.

**Comment by rpkilby** [comment]
Close this for now. In short, I think the problem is our application code. Reference this [post](http://lisperator.net/uglifyjs/mangle) on name mangling. 

I'll look into this more later, but I'm 99% sure the problem is that our API performs type introspection based on `Function.name`. These types are located in the app's model definitions. With the API isolated, there are no models to introspect. With the app isolated, there's no code that attempts to introspect the types. When we try to bundle both together, the mangler shortens the `Function.name`s and causes the introspecting code to fail.
