### ISSUE TITLE
Cannot read property 'parameters' of undefined

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#524]
@guybedford Please note the jspm version numbers here.

My `buildStatic()` works fine with 0.16.29 and fails as shown below with 0.16.30. 

I tried with 0.16.31, but that fails with a swallowed exception. Nothing shows up at all other than an error in gulp.

Basically, I'm stuck at 0.16.29 now.

```
└─┬ jspm@0.16.30
  ├── systemjs@0.19.23
  └── systemjs-builder@0.15.10
```

```
TypeError: Error compiling amd module "github:taye/interact.js@stable/interact.js" at jspm_packages/github/taye/interact.js@stable/interact.js
	Cannot read property 'parameters' of undefined
  at ParseTreeTransformer.AMDDefineRegisterTransformer.transformCallExpression (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/compilers/amd.js:227:76)
  at CallExpression.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:6649:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformExpressionStatement (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9504:31)
  at ExpressionStatement.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7120:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformList (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9200:34)
  at ParseTreeTransformer.transformBlock (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9317:31)
  at Block.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:6612:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformToBlockOrStatement (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9217:32)
  at ParseTreeTransformer.transformIfStatement (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9634:29)
  at IfStatement.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7438:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformToBlockOrStatement (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9217:32)
  at ParseTreeTransformer.transformIfStatement (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9635:31)
  at IfStatement.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7438:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformList (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9200:34)
  at ParseTreeTransformer.transformFunctionBody (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9574:31)
  at FunctionBody.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7293:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformFunctionExpression (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9596:25)
  at ParseTreeTransformer.AMDDependenciesTransformer.transformFunctionExpression (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/compilers/amd.js:61:69)
  at FunctionExpression.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7339:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformCallExpression (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9327:28)
  at ParseTreeTransformer.AMDDefineRegisterTransformer.transformCallExpression (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/compilers/amd.js:185:67)
  at CallExpression.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:6649:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformParenExpression (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9844:31)
  at ParenExpression.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:8023:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformExpressionStatement (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9504:31)
  at ExpressionStatement.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:7120:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at ParseTreeTransformer.transformList (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9200:34)
  at ParseTreeTransformer.transformScript (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9861:35)
  at Script.$__super.transform (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:8079:28)
  at ParseTreeTransformer.transformAny (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:9193:44)
  at Object.exports.compile (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/compilers/amd.js:376:22)
  at /Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:109:43
  at tryCatcher (/Users/jon/checkout/hub/node_modules/jspm/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/jon/checkout/hub/node_modules/jspm/node_modules/bluebird/js/release/promise.js:503:31)
  at Promise._settlePromise (/Users/jon/checkout/hub/node_modules/jspm/node_modules/bluebird/js/release/promise.js:560:18)
  at Promise._settlePromiseCtx (/Users/jon/checkout/hub/node_modules/jspm/node_modules/bluebird/js/release/promise.js:597:10)
  at Async._drainQueue (/Users/jon/checkout/hub/node_modules/jspm/node_modules/bluebird/js/release/async.js:131:12)
  at Async._drainQueues (/Users/jon/checkout/hub/node_modules/jspm/node_modules/bluebird/js/release/async.js:136:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/jon/checkout/hub/node_modules/jspm/node_modules/bluebird/js/release/async.js:16:14)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by guybedford** [comment]
@lookfirst I think the issue you've posted was exactly the one fixed in https://github.com/systemjs/builder/commit/f024acff22a90371e9b3222daccdad5a80e86da7, so I'd suggest trying to track down the swallowed error here if you can perhaps share a replication.

**Comment by lookfirst** [comment]
@guybedford Ok, if I apply that single fix to 0.16.30, things work just fine. So, now it is something between .30 and .31 that is breaking. I'm not really sure how to track down the swallowed error. =(

**Comment by guybedford** [comment]
If you can send a replication that would be a start.

**Comment by lookfirst** [comment]
@guybedford  Coming up with a replication is nearly impossible at this point. Is there anything in the differences that could point at the problem or at least enable me to be able to debug it more easily?

**Comment by guybedford** [comment]
A swallowed error is itself another bug certainly. I seem to recall this may be related to parsing with Traceur somehow. The way to check this would be to log `load.name` in https://github.com/systemjs/builder/blob/master/compilers/esm.js#L90 to see which dependency is being processed when it is swallowed.

Another method here would be to comment out imports running an effective binary search that way to discover what the dependency is causing the problem to provide an isolation of the exact dependency file causing the problem.

**Comment by guybedford** [comment]
Did you manage to make any further progress here?

**Comment by lookfirst** [comment]
Haven't had time, sorry @guybedford. Should I also just focus on moving to .17 instead?

**Comment by guybedford** [comment]
Yes I would advise everyone upgrade to 0.17 as the release is only pending the docs update.

**Comment by lookfirst** [comment]
I'm going to close this as I'm moving to 0.17 and don't see this same issue anymore.
