### ISSUE TITLE
UglifyJS fail using jspm bundle --minify but succeeds without minification

### ISSUE THREAD

**Issue by jesselegg** [systemjs/builder#56]
I'm experiencing a problem when running `jspm bundle`. I have created the following test file and placed it in `app/jspm-test`. This snippet replicates the problem section of code in a large asm.js project. It is valid Javascript syntax.

```javascript
function k(ra){throw ra;}var n=void 0,r=!0,t=null,A=!1;
```

If I run `jspm bundle app/jspm-test build/jspm-test.bundle.js` the bundle succeeds. 

```bash
$ jspm bundle app/jspm-test public/build/jspm-test.bundle.js
     Building the bundle tree for app/jspm-test...
ok   Built into public/build/jspm-test.bundle.js with source maps, unminified.
```

However, when I add the `--minify` flag, we get a failure in uglifyjs. 

```bash
$ jspm bundle app/jspm-test public/build/jspm-test.bundle.js --minify
     Building the bundle tree for app/jspm-test...

err  Error
         at new JS_Parse_Error (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:189:18)
         at js_error (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:197:11)
         at croak (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:657:9)
         at token_error (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:665:9)
         at unexpected (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:671:9)
         at expr_atom (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1167:9)
         at maybe_unary (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1328:19)
         at expr_ops (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1363:24)
         at maybe_conditional (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1368:20)
         at maybe_assign (/usr/local/lib/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1392:20)
```

If I bundle without `--minify` and then manually run uglifyjs I get the same error, but with more detail:

```bash
$ uglifyjs jspm-test.bundle.js -m -o test.min.js
Parse error at jspm-test.bundle.js:8,7
Unexpected token: keyword (var)
Error
    at new JS_Parse_Error (/usr/local/lib/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/usr/local/lib/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/usr/local/lib/node_modules/uglify-js/lib/parse.js:657:9)
    at token_error (/usr/local/lib/node_modules/uglify-js/lib/parse.js:665:9)
    at unexpected (/usr/local/lib/node_modules/uglify-js/lib/parse.js:671:9)
    at expr_atom (/usr/local/lib/node_modules/uglify-js/lib/parse.js:1167:9)
    at maybe_unary (/usr/local/lib/node_modules/uglify-js/lib/parse.js:1328:19)
    at expr_ops (/usr/local/lib/node_modules/uglify-js/lib/parse.js:1363:24)
    at maybe_conditional (/usr/local/lib/node_modules/uglify-js/lib/parse.js:1368:20)
    at maybe_assign (/usr/local/lib/node_modules/uglify-js/lib/parse.js:1392:20)
```

The unminified bundle output appears as so:
```javascript
"format register";

System.register("app/jspm-test", [], false, function(__require, __exports, __module) {
  System.get("@@global-helpers").prepareGlobal(__module.id, []);
  (function() {
    (function k(ra) {
      throw ra;
    }, var n = void 0,
        r = !0,
        t = null,
        A = !1;, this["n"] = n;, this["r"] = r;, this["t"] = t;, this["A"] = A;);
  }).call(System.global);
  return System.get("@@global-helpers").retrieveGlobal(__module.id, false);
});

//# sourceMappingURL=jspm-test.bundle.js.map
```

Line 8 `}, var n = void 0,` is the problem as it's not valid Javascript syntax. I believe this was generated by the SystemJS builder. Am I correct in this thinking? If so, it seems like a bug? Or is SystemJS leveraging some other library to do this generation and the bug lies there? Any suggestions on workaround or fix? Thanks!

This is jspm 0.10.6, uglifyjs 2.4.16, systemjs-builder 0.5.3.

**Comment by guybedford** [comment]
I've just tested this in the latest master of jspm, which will be released tomorrow as jspm@0.11 with  Traceur 0.0.82 and it's not happening for me.

Try it once this release is out (or run this master branch), and let me know if it's still happening?

**Comment by jesselegg** [comment]
Wow, good timing! I tested with jspm@0.11 this morning with both my example case above and my larger asm.js project. Everything bundles and loads in the browser. Thanks for the great tool.

**Comment by guybedford** [comment]
Awesome, glad to hear that!
