### ISSUE TITLE
Negation in Bundle Arithmetic possible?

### ISSUE THREAD

**Issue by filipesilva** [systemjs/builder#563]
Is it currently possible to have negation in the bundle arithmetic? I've been trying without much success, so I suppose not but I might just have missed something.

In "Third-Party Dependency Bundles" example, you show this:

```
builder.bundle('app/**/* - [app/**/*]', 'dependencies.js', { minify: true, sourceMaps: true });
```

In my case, I was trying to do roughly the opposite of that and bundle everything *except* third party stuff (also having a single entry point).

```
builder.bundle('main.ts - ![app/**/*]', 'dependencies.js', { minify: true, sourceMaps: true });
```

**Comment by guybedford** [comment]
We recently supported parens so that should work via:

```
builder.bundle('main.ts - (app/**/* - [app/**/*])', ..)
```

**Comment by filipesilva** [comment]
Oh, that makes sense. Cheers!

**Comment by filipesilva** [comment]
Heya, I was using your recommendation today and came across an issue with maps, it seems.

Doing `builder.bundle('app/index.js', 'outfile.js')` is fine, and so is `builder.bundle('app/index.js - [app/**/*]', 'outfile.js')`. They produce an `outfile.js` with everything, and everything except the contents of `app`.

Running `builder.bundle('app/index.js - (app/**/* - [app/**/*])', 'outfile.js')` throws an error though:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/dev/ideablade/testing/testproj4 (master)
$ node script.js
Build error
{ [Error: Error on instantiate for app/environment.js.map at file:///E:/dev/ideablade/testing/testproj4/dist/app/environment.js.map
        SyntaxError: Unexpected token :
            at Object.exports.runInThisContext (vm.js:53:16)
            at SystemJSNodeLoader.loader.instantiate (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\compilers\amd.js:292:30)
            at SystemJSNodeLoader.loader.instantiate (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\compilers\esm.js:54:32)
            at E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\lib\trace.js:443:25
            at tryCatcher (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:16:23)
            at Promise._settlePromiseFromHandler (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:502:31)
            at Promise._settlePromise (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:559:18)
            at Promise._settlePromise0 (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:604:10)
            at Promise._settlePromises (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:683:18)
            at Async._drainQueue (E:\dev\ideablade\testing\testproj4\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:138:16)
        Evaluating E:/dev/ideablade/testing/testproj4/dist/app/environment.js.map] originalErr: [SyntaxError: Unexpected token :] }
```

Should this happen? It seems kinda weird to have an error on a map file.

**Comment by guybedford** [comment]
`**/*` will catch source maps in the `app` folder. Perhaps try `**/*.js`.
