### ISSUE TITLE
Ascii option is gone which causes weird stacktrace....

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#573]
If I set `minify: true` as part of my `builder.buildStatic()`, then I get the following error. If I set it false, things work just fine.

```
Error: Error
  at formatError (/project/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/project/node_modules/gulp/bin/gulp.js:195:15)
  at emitOne (events.js:95:20)
  at Gulp.emit (events.js:182:7)
  at Gulp.Orchestrator._emitTaskDone (/project/node_modules/orchestrator/index.js:264:8)
  at /project/node_modules/orchestrator/index.js:275:23
  at finish (/project/node_modules/orchestrator/lib/runTask.js:21:8)
  at /project/node_modules/orchestrator/lib/runTask.js:45:4
  at tryCatcher (/project/node_modules/jspm/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/project/node_modules/jspm/node_modules/bluebird/js/release/promise.js:502:31)
  at Promise._settlePromise (/project/node_modules/jspm/node_modules/bluebird/js/release/promise.js:559:18)
  at Promise._settlePromise0 (/project/node_modules/jspm/node_modules/bluebird/js/release/promise.js:604:10)
  at Promise._settlePromises (/project/node_modules/jspm/node_modules/bluebird/js/release/promise.js:679:18)
  at Async._drainQueue (/project/node_modules/jspm/node_modules/bluebird/js/release/async.js:138:16)
  at Async._drainQueues (/project/node_modules/jspm/node_modules/bluebird/js/release/async.js:148:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/project/node_modules/jspm/node_modules/bluebird/js/release/async.js:17:14)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by lookfirst** [comment]
For reference, the file that gets output with `minify: false` runs through uglifyjs on the cli just fine.

**Comment by lookfirst** [comment]
Ah, I finally figured it out by adding a buildStatic().catch((err) => { console.log(err) }); and got:

```
  msg: '`ascii` is not a supported option',
```

It looks like you removed the ascii option?

**Comment by lookfirst** [comment]
Solution: `uglify: {beautify: {ascii_only: true}}`

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/systemjs/builder/commit/18b3ba48487c1b5c788627605e201e95a2cccc12, although that is exactly the better way as this is backwards compat at this point.
