### ISSUE TITLE
"SyntaxError: Unexpected token", but no line number

### ISSUE THREAD

**Issue by juergenzimmermann** [systemjs/builder#575]
I'm getting the following stacktrace, but have no idea where I should start searching for the causing error.
My JS files are the result of TypeScript compilation, and I want to bundle them together with Angular 2.
````
Unhandled rejection Error: Error on dependency parsing for dist/buchverwaltung/service/mock/buecher_service_mock_server.js at file:///c:/temp/angular/dist/buchverwaltung/service/mock/buecher_service_mock_server.js
        Loading dist/app/main.js
        Loading dist/app/app.js
        SyntaxError: Unexpected token =
            at Object.exports.runInThisContext (vm.js:53:16)
            at SystemJSNodeLoader.loader.instantiate (c:\temp\angular\node_modules\systemjs-builder\compilers\amd.js:292:30)
            at SystemJSNodeLoader.loader.instantiate (c:\temp\angular\node_modules\systemjs-builder\compilers\esm.js:54:32)
            at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:436:25
            at bound (domain.js:287:14)
            at runBound (domain.js:300:12)
            at tryCatcher (c:\temp\angular\node_modules\bluebird\js\release\util.js:16:23)
            at Promise._settlePromiseFromHandler (c:\temp\angular\node_modules\bluebird\js\release\promise.js:502:31)
            at Promise._settlePromise (c:\temp\angular\node_modules\bluebird\js\release\promise.js:559:18)
            at Promise._settlePromise0 (c:\temp\angular\node_modules\bluebird\js\release\promise.js:604:10)
        Evaluating c:/temp/angular/dist/buchverwaltung/service/mock/buecher_service_mock_server.js
            at Object.exports.runInThisContext (vm.js:53:16)
            at SystemJSNodeLoader.loader.instantiate (c:\temp\angular\node_modules\systemjs-builder\compilers\amd.js:292:30)
            at SystemJSNodeLoader.loader.instantiate (c:\temp\angular\node_modules\systemjs-builder\compilers\esm.js:54:32)
            at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:436:25
            at bound (domain.js:287:14)
            at runBound (domain.js:300:12)
            at Object.exports.runInThisContext (vm.js:53:16)
            at SystemJSNodeLoader.loader.instantiate (c:\temp\angular\node_modules\systemjs-builder\compilers\amd.js:292:30)
            at SystemJSNodeLoader.loader.instantiate (c:\temp\angular\node_modules\systemjs-builder\compilers\esm.js:54:32)
            at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:436:25
            at bound (domain.js:287:14)
            at runBound (domain.js:300:12)
    at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:432:10
    at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:410:8
    at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:380:6
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
    at Trace.getLoadRecord (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:124:4)
    at Trace.getAllLoadRecords (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:560:15)
    at Trace.getAllLoadRecords (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:561:4)
    at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:52:19
    at Trace.traceCanonical (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:50:4)
    at c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:243:35
    at c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:232:20
    at Array.reduce (native)
    at processExpandedOperations (c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:231:35)
    at exports.traceExpression (c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:229:8)
    at c:\temp\angular\node_modules\systemjs-builder\lib\builder.js:669:14
    at c:\temp\angular\node_modules\systemjs-builder\lib\builder.js:668:6
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
    at Builder.buildStatic (c:\temp\angular\node_modules\systemjs-builder\lib\builder.js:660:4)
    at gulpfile.babel.js:239:29
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
    at angularBundle (gulpfile.babel.js:236:13)
    at taskWrapper (c:\temp\angular\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (c:\temp\angular\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3
From previous event:
    at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:491:13
From previous event:
    at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:380:6
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Trace.getLoadRecord (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:124:4)
    at Trace.getAllLoadRecords (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:560:15)
From previous event:
    at Trace.getAllLoadRecords (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:561:4)
    at c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:52:19
From previous event:
    at Trace.traceCanonical (c:\temp\angular\node_modules\systemjs-builder\lib\trace.js:50:4)
    at c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:243:35
From previous event:
    at c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:232:20
    at Array.reduce (native)
    at processExpandedOperations (c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:231:35)
From previous event:
    at exports.traceExpression (c:\temp\angular\node_modules\systemjs-builder\lib\arithmetic.js:229:8)
    at c:\temp\angular\node_modules\systemjs-builder\lib\builder.js:669:14
From previous event:
    at c:\temp\angular\node_modules\systemjs-builder\lib\builder.js:668:6
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Builder.buildStatic (c:\temp\angular\node_modules\systemjs-builder\lib\builder.js:660:4)
    at gulpfile.babel.js:239:29
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
From previous event:
    at angularBundle (gulpfile.babel.js:236:13)
    at taskWrapper (c:\temp\angular\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (c:\temp\angular\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3
````

**Comment by gaetancollaud** [comment]
I have the exact same issue but only when I run system-builder through maven. When I run the task directly with gulp or through npm the task is successful.

I use maven frontend-plugin -> npm -> gulp to run system builder.

**Comment by gaetancollaud** [comment]
I solve this issue by compiling my typescript code to ES5 and not ES6.
