### ISSUE TITLE
Broken @import declaration of "todomvc-app-css/index.css"

### ISSUE THREAD

**Issue by micaelmbagira** [systemjs/builder#609]
I have this import of css `import 'todomvc-app-css/index.css!';`.
When I run `builer.buildStatic`, I get the following error:
> Broken @import declaration of "todomvc-app-css/index.css"
    at SystemJSNodeLoader.exports.bundle (file:///webapp/jspm_packages/github/systemjs/plugin-css@0.1.22/css-builder.js:76:13)
    at file:///webapp/jspm_packages/github/systemjs/plugin-css@0.1.22/css.js:110:29
    at run webapp/node_modules/core-js/modules/es6.promise.js:89:22)

I am using jspm `0.17.0-beta.16` and plugin-css `0.1.22`.

**Comment by micaelmbagira** [comment]
The import was not properly made on my side.
