### ISSUE TITLE
Error bundling external css

### ISSUE THREAD

**Issue by GlurG** [systemjs/builder#661]
Upon building my project using the following script:
```
"use strict";

const Builder = require("systemjs-builder");
const builder = new Builder("client/", "client/jspm.config.js");

builder.bundle("js/boot.js", "client/js/app.min.js", {
	//"externals": ["font-awesome.css"]
});
```
I get the following error:
```
err  Error on fetch for cdn:font-awesome/4.6.1/css/font-awesome.min.css at https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.min.css
  Loading js/boot.js
  Error: Unable to fetch "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.min.css". Only file URLs of the form file:/// allowed running in Node.
    at fetchTextFromURL (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:1067:15)
    at C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:1782:7
    at SystemJSNodeLoader.<anonymous> (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:1781:12)
    at SystemJSNodeLoader.<anonymous> (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:2810:22)
    at SystemJSNodeLoader.<anonymous> (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:3384:20)
    at SystemJSNodeLoader.<anonymous> (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:3696:18)
    at SystemJSNodeLoader.<anonymous> (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:4088:18)
    at SystemJSNodeLoader.<anonymous> (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:4551:22)
    at SystemJSNodeLoader.fetch (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs\dist\system.src.js:4820:20)
    at SystemJSNodeLoader.cachedFetch (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:178:40)
    at SystemJSNodeLoader.loader.fetch (C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:198:26)
    at C:\Projects\spoils-toolbox\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:434:12
    at tryCatcher (C:\Projects\spoils-toolbox\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Projects\spoils-toolbox\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Projects\spoils-toolbox\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Projects\spoils-toolbox\node_modules\bluebird\js\release\promise.js:606:10)
```
`boot.js` is completely empty, the relevant `jspm.config.js` is as follows:
```
SystemJS.config({
  // ...
  nodeConfig: {
    "paths": {
      "npm:": "jspm_packages/npm/",
      "github:": "jspm_packages/github/",
      "cdn:": "https://cdnjs.cloudflare.com/ajax/libs/"
    }
  },
  //...
  meta: {
    "*.css": {
      "loader": "css"
    },
    "js/boot.js": {
      "deps": [
        "font-awesome.css"
      ]
    }
  }
  //...
  map: {
    "font-awesome.css": "cdn:font-awesome/4.6.1/css/font-awesome.min.css",
  }
});
```
The error appeared in version 0.15.24, and is present in 0.15.25 and 0.15.26.
If I de-comment the `//"externals": ["font-awesome.css"]` line, the build succeeds in the aforementioned versions. I'm using css-loader v0.1.26.
Is this error intentional?

**Comment by guybedford** [comment]
The reason for this is that we allow loaders (like the CSS loader) to use custom namespaces, so non fileURLs are not automatically included as externals.

We could add an exception in the CSS plugin itself, where it automatically notes that these are externals, but it's probably best just to leave in the externals array for now.
