### ISSUE TITLE
SystemJS builder crashes on array destructuring code

### ISSUE THREAD

**Issue by MaximBalaganskiy** [systemjs/builder#687]
I'm trying to bundle a system js module with the code which has array destructuring.
```
var a, b;
[a, b] = [1, 2];
```
and get an exception
```
(SystemJS) Invalid left-hand side in assignment
	ReferenceError: Invalid left-hand side in assignment
	    at Object.exports.runInThisContext (vm.js:53:16)
	    at SystemJSNodeLoader.loader.instantiate (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\compilers\amd.js:292:30)
	    at SystemJSNodeLoader.loader.instantiate (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\compilers\esm.js:54:32)
	    at C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\lib\trace.js:485:25
	    at tryCatcher (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:16:23)
	    at Promise._settlePromiseFromHandler (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:510:31)
	    at Promise._settlePromise (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:567:18)
	    at Promise._settlePromise0 (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:612:10)
	    at Promise._settlePromises (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.js:691:18)
	    at Async._drainQueue (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:138:16)
	    at Async._drainQueues (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:148:10)
	    at Immediate.Async.drainQueues [as _onImmediate] (C:\Dev\AquaWeb\src\AquaWeb.Portal\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:17:14)
	    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by guybedford** [comment]
You would need to enable Babel for CommonJS files here with a configuration like:

```javascript
System.config({
  meta: {
    'cjs/*.js': {
      format: 'cjs',
      loader: 'babel'
    }
  }
});
```
