### ISSUE TITLE
Weirdest error

### ISSUE THREAD

**Issue by Dashue** [systemjs/builder#706]
`[23:38:46] 'app.systemjs.bundle' errored after 634 ms
[23:38:46] evalmachine.<anonymous>:5
declare var System: any;
        ^^^
SyntaxError: Unexpected token var
    at Object.exports.runInNewContext (vm.js:48:16)
    at Builder.executeConfigFile (C:\Dev\Proffy\node_modules\systemjs-builder\lib\builder.js:300:17)
    at Builder.loadConfigSync (C:\Dev\Proffy\node_modules\systemjs-builder\lib\builder.js:310:21)
    at new Builder (C:\Dev\Proffy\node_modules\systemjs-builder\lib\builder.js:54:10)
    at C:\Dev\Proffy\gulpfile.js:33:19
    at taskWrapper (C:\Dev\Proffy\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (C:\Dev\Proffy\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

gulpfile.js
var paths = {
    build: "build",
    dest: "wwwroot/",
    styles: "app/**/*/less",
    viewsFolder: "app/views/",
    ts: "app/**/*.ts"
}
var SystemBuilder = require('systemjs-builder');
function compileTypescript() {
    var tsResult = gulp.src(paths.ts)
        .pipe(tsProject());

    return tsResult.js
        .pipe(gulp.dest('build/js'));
}

gulp.task('app.systemjs.bundle', function () {
    var builder = new SystemBuilder('build/js', './system.config.js');
    return builder.buildStatic('main.js', 'wwwroot/app.bundle.js');
});

gulp.task('dev', gulp.series(
    clean,
    copyLibs,
    copyViews,
    compileTypescript,
    'app.systemjs.bundle',
    compileStyles,
    watch
));

tsconfig.json
{
    "compilerOptions": {
        "diagnostics": true,
        "noEmitOnError": true,
        // "outFile": "app.js",
        "module": "system",
        "moduleResolution": "node",
        "target": "es6",
        "noImplicitAny": false,
        "rootDir": "app",
        "sourceMap": true,
        "inlineSourceMap": true,
        "experimentalDecorators": true
    },
    "files": [
        // "app/main.ts"
        // "typings/tsd.d.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}

main.ts
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule);

app.module.ts
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent }   from './app.component';

@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }

app.component.ts
import { Component } from '@angular/core';
@Component({
  selector: 'my-app',
  template: '<h1>My First Angular App</h1>'
})

export class AppComponent { }

main.js
System.register(['@angular/platform-browser-dynamic', './app.module'], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var platform_browser_dynamic_1, app_module_1;
    var platform;
    return {
        setters:[
            function (platform_browser_dynamic_1_1) {
                platform_browser_dynamic_1 = platform_browser_dynamic_1_1;
            },
            function (app_module_1_1) {
                app_module_1 = app_module_1_1;
            }],
        execute: function() {
            platform = platform_browser_dynamic_1.platformBrowserDynamic();
            platform.bootstrapModule(app_module_1.AppModule);
        }
    }
});

Been bashing my head against this for a few hours now, I'm sure I'm doing something wrong but this is my first rodeo with systemjsbuilder so can't figure it out. Hope someone will be able to help.

**Comment by Dashue** [comment]
d'oh nvm
