### ISSUE TITLE
SystemJS bundle - error output does not show actual file paths

### ISSUE THREAD

**Issue by muralisaripalli** [systemjs/builder#710]
In 0.17 I have used 
jspm bundle mygame gamebundle.js -wd --source-map-contents
for development bundling

The following error output is thrown at a particular point

system.src.js:122 Uncaught (in promise) Error: (SystemJS) t.emit is not a function
	TypeError: t.emit is not a function
	    at i.addChild (http://192.168.1.177:3000/common/js/lib/min/pixi.min.js:10:15858)
	    at PercentageTextSkin.EaselSkin.addToContainer (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:40480:37)
	    at StageCoolINFOApp.StageCoolApp.initializeGameForINFO (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:45281:33)
	    at new StageCoolINFOApp (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:45430:17)
	    at execute (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:45522:14)
	Error loading http://192.168.1.177:3000/mygame/src/App.js
	    at i.addChild (http://192.168.1.177:3000/common/js/lib/min/pixi.min.js:10:15858)
	    at PercentageTextSkin.EaselSkin.addToContainer (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:40480:37)
	    at StageCoolINFOApp.StageCoolApp.initializeGameForINFO (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:45281:33)
	    at new StageCoolINFOApp (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:45430:17)
	    at execute (http://192.168.1.177:3000/mygame/public/js/gamebundle.js:45522:14)
	Error loading http://192.168.1.177:3000/mygame/src/App.js

Is there a way we can see the actual file name where the error occurred instead of gamebundle.js

**Comment by guybedford** [comment]
Are the source maps applying in the `sources` tab correctly for you here?

**Comment by guybedford** [comment]
Let me know if this is resolved in the latest release for you.

**Comment by muralisaripalli** [comment]
I still see the bundle file path in the error output. 
FYI, the browser apply sourcemaps correctly later, for the run time errors after the application is loaded.

The above error message is from jspm. I see this when I click the (...) at the end of the error summary in console. Is this how its supposed to be? As mentioned above, Chrome shows me correct paths for run time errors after the application is initiated.

For reference, the entry point file Main.js 
```
import StageCoolINFOApp from "mygame/StageCoolINFOApp";
var game = new StageCoolINFOApp();
```

Bundle command I am using
`jspm bundle mygame gamebundle.js -wd`

The script tag
```
<script src='./js/gamebundle.js'></script>
<script type="text/javascript">
    System.import("mygame");
</script>
```

**Comment by guybedford** [comment]
If I remember correctly, I think this is a Chrome issue actually that source maps take a little while to load so execution errors don't do the full source maps lookup.

**Comment by muralisaripalli** [comment]
I see the same error output in internet explorer, showing the bundle file path.

This is not a blocker for me. But do you think this is related to source maps? I might be wrong, but my understanding was that this could be an internal jspm thing as the error description is from jspm.

I am not sure how browser and libraries interpret. Please correct me if I am wrong.
