### ISSUE TITLE
Common Bundle issue

### ISSUE THREAD

**Issue by mikesnare** [systemjs/builder#724]
I have split my app into several separate bundles and that's working well.  One of my bundles is the 'main' bundle that bootstraps my app and lazily loads other modules as necessary.  All that's working well.

Several of my lazy modules use the same rather large third party dependency, so I'd like to just add that to the main bundle so that the lazy bundles are smaller.

The approach I'm trying to take is roughly as follows:

```js
// First create a bundle of the third party dependencies.
builder.bundle('app/dist/app/app/**/* - [app/dist/app/app/**/*]', 'dist/lib/dependencies.js', {minify: true})

// Now create a bundle containing the main app combined with the dependencies generated above.
builder.bundle('app/dist/app/app/main.js + app/dist/lib/dependencies.js', 'dist/lib/bundle.js', {minify: true})

// Now create the lazy bundles, hopefully minus anything that's already in the main bundle
builder.bundle('someLazyModule.js - app/dist/lib/bundle.js', 'dist/lib/someLazyModule.js', {minify: true})
```

(Note that the above steps are chained so that each step only begins when the previous step is complete)

Step one works.  The third party bundle looks to be correct.

Step two fails (stack trace below).

Step 3 (and beyond for other lazy modules) works providing that in step two I do not attempt to add the third party code to the main bundle.

What am I doing wrong?  From the README it seems like this should work.

```
TypeError: Cannot read property 'forEach' of undefined
    at Trace.getLoadDependencies (app/node_modules/systemjs-builder/lib/trace.js:934:12)
    at traverseTree (app/node_modules/systemjs-builder/lib/arithmetic.js:377:16)
    at app/node_modules/systemjs-builder/lib/arithmetic.js:382:9
    at Array.forEach (native)
    at traverseTree (app/node_modules/systemjs-builder/lib/arithmetic.js:380:10)
    at app/node_modules/systemjs-builder/lib/arithmetic.js:382:9
    at Array.forEach (native)
    at traverseTree (app/node_modules/systemjs-builder/lib/arithmetic.js:380:10)
    at app/node_modules/systemjs-builder/lib/compile.js:156:5
    at Array.forEach (native)
    at getTreeModulesPostOrder (app/node_modules/systemjs-builder/lib/compile.js:155:14)
    at compileTree (app/node_modules/systemjs-builder/lib/compile.js:269:17)
    at app/node_modules/systemjs-builder/lib/builder.js:700:14
    at tryCatcher (app/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (app/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (app/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:567:18)
```

**Comment by guybedford** [comment]
This does sound like a bug. If you're able to share a replication at all that would help. Otherwise perhaps test against the master branch to see if it's working there already.

**Comment by mikesnare** [comment]
Same thing happens on master.  I can't easily get you a replication any time soon, unfortunately.  I'll look into it, but it won't be quick.

I may try switching to traces instead of files and see if that works any better.
