### ISSUE TITLE
Problem with Lazy Bundle Loading

### ISSUE THREAD

**Issue by avol-io** [systemjs/builder#739]
My purpose is creating some module bundles and loading few of them in lazy mode.

I tried two ways:

1. build main module and only one child module, each module includes all dependencies (i would like to avoid it).  -> app starts and when the user will go to page that links to a module that is in another bundle the following happens:
a) the app downloads the lazy loaded bundle 
b) angular2 finds the module into the bundle 
c) it fails to compare module metadata with it’s definition of ngmodule metadata (see details above)
2. build depedencies module, main module and one child module, the last two are builded without depedencies modules (my desired behaviour) -> fail: error is  “app.js:3144 Uncaught Error: Module must be loaded as AMD or CommonJS(…)”

## Way 1:
my gulp snippet about bundle:

```
gulp.task('app-bundle', function() {
    return builder.buildStatic('dist/app/**/* ', 'build/scripts/app.js');
});

gulp.task('lazy-bundle', function() {
    return builder.buildStatic('dist/app/modules/section1/**/*', 'build/scripts/lazybundle.js');
});
```

**error**
When users open the link that triggers the lazy module the error is: 
```
**VM2137:27 EXCEPTION: Uncaught (in promise): Error: No NgModule metadata found for 'Section1Module'.**
Error: No NgModule metadata found for 'Section1Module'.
    at NgModuleResolver.resolve (http://127.0.0.1:8081/scripts/app.js:13533:17)
    at CompileMetadataResolver.getNgModuleMetadata (http://127.0.0.1:8081/scripts/app.js:13757:43)
    at RuntimeCompiler._compileComponents (http://127.0.0.1:8081/scripts/app.js:16228:45)
    at RuntimeCompiler._compileModuleAndComponents (http://127.0.0.1:8081/scripts/app.js:16170:35)
    at RuntimeCompiler.compileModuleAsync (http://127.0.0.1:8081/scripts/app.js:16161:19)
    at ModuleBoundCompiler.compileModuleAsync (http://127.0.0.1:8081/scripts/app.js:16499:29)
    at http://127.0.0.1:8081/scripts/app.js:82149:32
    at ZoneDelegate.invoke (http://127.0.0.1:8081/scripts/polyfill.js:7497:26)
    at Object.onInvoke (http://127.0.0.1:8081/scripts/app.js:81385:29)
    at ZoneDelegate.invoke (http://127.0.0.1:8081/scripts/polyfill.js:7496:32)window.console.error @ VM2137:27ErrorHandler.handleError @ app.js:78910next @ app.js:81719EventEmitter.subscribe.schedulerFn @ app.js:81202$__System.registerDynamic.SafeSubscriber.__tryOrUnsub @ app.js:76788$__System.registerDynamic.SafeSubscriber.next @ app.js:76743$__System.registerDynamic.Subscriber._next @ app.js:76697$__System.registerDynamic.Subscriber.next @ app.js:76661$__System.registerDynamic.Subject.next @ app.js:76167EventEmitter.emit @ app.js:81186NgZone.triggerError @ app.js:81426onHandleError @ app.js:81402ZoneDelegate.handleError @ polyfill.js:7501Zone.runGuarded @ polyfill.js:7396_loop_1 @ polyfill.js:7677drainMicroTaskQueue @ polyfill.js:7686ZoneTask.invoke @ polyfill.js:7604
VM2137:27 ORIGINAL STACKTRACE:window.console.error @ VM2137:27ErrorHandler.handleError @ app.js:78915next @ app.js:81719EventEmitter.subscribe.schedulerFn @ app.js:81202$__System.registerDynamic.SafeSubscriber.__tryOrUnsub @ app.js:76788$__System.registerDynamic.SafeSubscriber.next @ app.js:76743$__System.registerDynamic.Subscriber._next @ app.js:76697$__System.registerDynamic.Subscriber.next @ app.js:76661$__System.registerDynamic.Subject.next @ app.js:76167EventEmitter.emit @ app.js:81186NgZone.triggerError @ app.js:81426onHandleError @ app.js:81402ZoneDelegate.handleError @ polyfill.js:7501Zone.runGuarded @ polyfill.js:7396_loop_1 @ polyfill.js:7677drainMicroTaskQueue @ polyfill.js:7686ZoneTask.invoke @ polyfill.js:7604
VM2137:27 Error: Uncaught (in promise): Error: No NgModule metadata found for 'Section1Module'.
Error: No NgModule metadata found for 'Section1Module'.
    at NgModuleResolver.resolve (app.js:13533)
    at CompileMetadataResolver.getNgModuleMetadata (app.js:13757)
    at RuntimeCompiler._compileComponents (app.js:16228)
    at RuntimeCompiler._compileModuleAndComponents (app.js:16170)
    at RuntimeCompiler.compileModuleAsync (app.js:16161)
    at ModuleBoundCompiler.compileModuleAsync (app.js:16499)
    at app.js:82149
    at ZoneDelegate.invoke (polyfill.js:7497)
    at Object.onInvoke (app.js:81385)
    at ZoneDelegate.invoke (polyfill.js:7496)
    at resolvePromise (polyfill.js:7733)
    at polyfill.js:7710
    at ZoneDelegate.invoke (polyfill.js:7497)
    at Object.onInvoke (app.js:81385)
    at ZoneDelegate.invoke (polyfill.js:7496)
    at Zone.run (polyfill.js:7379)
    at polyfill.js:7767
    at ZoneDelegate.invokeTask (polyfill.js:7530)
    at Object.onInvokeTask (app.js:81377)
    at ZoneDelegate.invokeTask (polyfill.js:7529)window.console.error @ VM2137:27ErrorHandler.handleError @ app.js:78916next @ app.js:81719EventEmitter.subscribe.schedulerFn @ app.js:81202$__System.registerDynamic.SafeSubscriber.__tryOrUnsub @ app.js:76788$__System.registerDynamic.SafeSubscriber.next @ app.js:76743$__System.registerDynamic.Subscriber._next @ app.js:76697$__System.registerDynamic.Subscriber.next @ app.js:76661$__System.registerDynamic.Subject.next @ app.js:76167EventEmitter.emit @ app.js:81186NgZone.triggerError @ app.js:81426onHandleError @ app.js:81402ZoneDelegate.handleError @ polyfill.js:7501Zone.runGuarded @ polyfill.js:7396_loop_1 @ polyfill.js:7677drainMicroTaskQueue @ polyfill.js:7686ZoneTask.invoke @ polyfill.js:7604
VM2137:27 Unhandled Promise rejection: No NgModule metadata found for 'Section1Module'. ; Zone: angular ; Task: Promise.then ; Value: Error: No NgModule metadata found for 'Section1Module'.(…) Error: No NgModule metadata found for 'Section1Module'.
    at NgModuleResolver.resolve (http://127.0.0.1:8081/scripts/app.js:13533:17)
    at CompileMetadataResolver.getNgModuleMetadata (http://127.0.0.1:8081/scripts/app.js:13757:43)
    at RuntimeCompiler._compileComponents (http://127.0.0.1:8081/scripts/app.js:16228:45)
    at RuntimeCompiler._compileModuleAndComponents (http://127.0.0.1:8081/scripts/app.js:16170:35)
    at RuntimeCompiler.compileModuleAsync (http://127.0.0.1:8081/scripts/app.js:16161:19)
    at ModuleBoundCompiler.compileModuleAsync (http://127.0.0.1:8081/scripts/app.js:16499:29)
    at http://127.0.0.1:8081/scripts/app.js:82149:32
    at ZoneDelegate.invoke (http://127.0.0.1:8081/scripts/polyfill.js:7497:26)
    at Object.onInvoke (http://127.0.0.1:8081/scripts/app.js:81385:29)
    at ZoneDelegate.invoke (http://127.0.0.1:8081/scripts/polyfill.js:7496:32)window.console.error @ VM2137:27consoleError @ polyfill.js:7653_loop_1 @ polyfill.js:7682drainMicroTaskQueue @ polyfill.js:7686ZoneTask.invoke @ polyfill.js:7604
VM2137:27 Error: Uncaught (in promise): Error: No NgModule metadata found for 'Section1Module'.(…)
```

**Here  is the point of fail in app.js (transpiled file of main bundle) :**
```
 function _isNgModuleMetadata(obj) {
    return obj instanceof _angular_core.NgModule;
  }
```

**Here is my opinion**
Obj is an instance of “ngModules” (it has as prototype DecoratorFactory) that come from lazybundle.js, but _angular_core.NgModule refers to “function DecoratorFactory” in app.js. 
Since I’m not excluding the common library (angular) it is loaded two times, one for bundle. So the piece of code it’s the same but javascript deals with it as two different classes because they are in two different files.
I try to separate the common library in the second way but it fail anyway.

## Way 2:
my gulp snippet:
```

gulp.task('app-deps', function() {
    return builder.buildStatic('dist/app/**/* - [dist/app/**/*]', 'build/scripts/deps.js');
});
gulp.task('app-bundle', function() {
    return builder.buildStatic(‘dist/app/main.js - (dist/app/**/* - [dist/app/**/*]) ', 'build/scripts/app.js'); 
});
gulp.task('lazy-bundle', function() {
    return builder.buildStatic('dist/app/modules/Section1/Section1.module.js - (dist/app/**/* - [dist/app/**/*]) ', 'build/scripts/lazybundle.js');
});
```

**main.ts**
```
import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";
import {AppModule} from "./app.module";
platformBrowserDynamic().bootstrapModule(AppModule);
```

**index.html**
```
<html>


<head>
    <base href="/">
    <title>sisp-core</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- inject:css -->
    <link rel="stylesheet" href="styles/vendor.min.css">
    <!-- endinject -->
</head>


<body>
    <main-application>Loading...</main-application>


    <!-- inject:js -->
    <script src="scripts/polyfill.js"></script>
    <script src="systemjs.config-building.js"></script>
    <script src="scripts/app.js"></script>
    <!-- endinject -->


</body>
</html>

```

**error:**
`app.js:3144 Uncaught Error: Module must be loaded as AMD or CommonJS(…)(anonymous function) @ app.js:3144(anonymous function) @ app.js:1(anonymous function) @ app.js:3138
`

**Here is the point of fail in app.js:**
```
(function(factory) {
  if (typeof define == 'function' && define.amd)
    define(["@angular/core","jquery","lodash","semantic","moment/moment.js","@angular/router","@angular/forms","@angular/http","rxjs/add/operator/toPromise.js","@angular/common","angular2-moment/index.js","rxjs/Rx.js","@angular/platform-browser","@angular/platform-browser-dynamic"], factory);
  else if (typeof module == 'object' && module.exports && typeof require == 'function')
    module.exports = factory(require("@angular/core"), require("jquery"), require("lodash"), require("semantic"), require("moment/moment.js"), require("@angular/router"), require("@angular/forms"), require("@angular/http"), require("rxjs/add/operator/toPromise.js"), require("@angular/common"), require("angular2-moment/index.js"), require("rxjs/Rx.js"), require("@angular/platform-browser"), require("@angular/platform-browser-dynamic"));
  else
    throw new Error("Module must be loaded as AMD or CommonJS");
});

```

I’m getting crazy about it, do you have any idea or suggestion about how to create with systemjs a production build that deals with lazy loading modules??

**Comment by aluanhaddad** [comment]
I am not a hundred percent sure but since you need runtime loader infrastructure to import the modules lazily, wouldn't it make more sense to use `bundle` instead of `buildStatic`. That way you could easily bundle the shared code and the common code flexibly.

**Comment by about-code** [comment]
I've just stumbled upon the same thing when bundling Angular with Rollup. You may be interested in angular/angular#14343

**Comment by dozer75** [comment]
@avol-io I got the same error today and I discovered that the `dist/app/**/*` syntax caused paths in registerDynamic to be absolute to the `dist/app` path which in turn causes your imports to fail since it can't find reference in your bundled files.

E.g. you have in your files `import { something } from "module/file";` these can't be found since the reference in registerDynamic has `dist/app/module/file`.

I didn't have any usage of using minimatch, so i just used a simple *.js, not sure what's best for you.

**Comment by snarun** [comment]
@avol-io .. Does this issue still persists? loading angular modules directly from UMD bundles at runtime???

**Comment by avol-io** [comment]
I switched to angular-cli / webpack. nowadays it's the best solution to have the lasted improvement features.
