### ISSUE TITLE
SyntaxError after upgrading Angular and systemjs-builder

### ISSUE THREAD

**Issue by juergenzimmermann** [systemjs/builder#770]
I upgraded Angular from 4.0.0-beta.6 to 4.0.0-beta.7, and systemjs-builder from 0.15.35 to 0.16.3 (and thus SystemJS from 0.19.43 to 0.20.7).
Now I'm getting the following stacktrace. Any hint is appreciated!
```
Unhandled rejection SyntaxError: node_modules/@angular/forms/src/directives/error_examples.js: 'import' and 'export' may appear only with 'sourceType: module' (14:4)
SyntaxError: node_modules/@angular/forms/src/directives/error_examples.js: 'import' and 'export' may appear only with 'sourceType: module' (14:4)
  12 |  * Use of this source code is governed by an MIT-style license that can be
  13 |  * found in the LICENSE file at https://angular.io/license
> 14 |  */ export var /** @type {?} */ FormErrorExamples = {
     |     ^
  15 |     formControlName: "\n    <div [formGroup]=\"myGroup\">\n      <input formControlName=\"firstName\">\n    </div>\n\n    In your class:\n\n    this.myGroup = new FormGroup({\n firstName: new FormControl()\n    });",
  16 |     formGroupName: "\n    <div [formGroup]=\"myGroup\">\n       <div formGroupName=\"person\">\n          <input formControlName=\"firstName\">\n       </div>\n    </div>\n\n    In your class:\n\n    this.myGroup = new FormGroup({\n       person: new FormGroup({ firstName: new FormControl() })\n    });",
  17 |     formArrayName: "\n    <div [formGroup]=\"myGroup\">\n      <div formArrayName=\"cities\">\n        <div *ngFor=\"let city of cityArray.controls; let i=index\">\n          <input[formControlName]=\"i\">\n        </div>\n      </div>\n    </div>\n\n    In your class:\n\n    this.cityArray = new FormArray([new FormControl('SF')]);\n    this.myGroup = new FormGroup({\n      cities: this.cityArray\n    });",
    at Parser.pp$5.raise (C:\workspace\software-entwicklung\angular\node_modules\babel-core\node_modules\babylon\lib\index.js:4333:13)
    at Parser.pp$1.parseStatement (C:\workspace\software-entwicklung\angular\node_modules\babel-core\node_modules\babylon\lib\index.js:1827:16)
    at Parser.pp$1.parseBlockBody (C:\workspace\software-entwicklung\angular\node_modules\babel-core\node_modules\babylon\lib\index.js:2212:21)
    at Parser.pp$1.parseTopLevel (C:\workspace\software-entwicklung\angular\node_modules\babel-core\node_modules\babylon\lib\index.js:1723:8)
    at Parser.parse (C:\workspace\software-entwicklung\angular\node_modules\babel-core\node_modules\babylon\lib\index.js:1617:17)
    at parse (C:\workspace\software-entwicklung\angular\node_modules\babel-core\node_modules\babylon\lib\index.js:6657:37)
    at File.parse (C:\workspace\software-entwicklung\angular\node_modules\babel-core\lib\transformation\file\index.js:527:15)
    at File.parseCode (C:\workspace\software-entwicklung\angular\node_modules\babel-core\lib\transformation\file\index.js:612:20)
    at C:\workspace\software-entwicklung\angular\node_modules\babel-core\lib\transformation\pipeline.js:49:12
    at File.wrap (C:\workspace\software-entwicklung\angular\node_modules\babel-core\lib\transformation\file\index.js:574:16)
    at Pipeline.transform (C:\workspace\software-entwicklung\angular\node_modules\babel-core\lib\transformation\pipeline.js:47:17)
    at Object.exports.compile (C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\compilers\compiler.js:30:20)
    at Object.exports.compile (C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\compilers\global.js:14:19)
    at C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\compile.js:117:43
From previous event:
    at compileLoad (C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\compile.js:116:6)
    at C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\compile.js:330:16
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\compile.js:324:8
    at Array.map (native)
    at C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\compile.js:322:32
From previous event:
    at compileTree (C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\compile.js:321:4)
    at C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\builder.js:774:16
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\builder.js:772:6
From previous event:
    at Builder.buildStatic (C:\workspace\software-entwicklung\angular\node_modules\systemjs-builder\lib\builder.js:769:4)
    at bundle.js:62:29
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
From previous event:
    at bundleFn (bundle.js:54:13)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (C:\workspace\software-entwicklung\angular\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by guybedford** [comment]
For this case you need to enforce the module format detection:

```javascript
System.config({
  meta: {
    'node_modules/@angular/forms/src/directives/error_examples.js': { format: 'esm' }
  }
});
```

It is probably best to be loading the angular build instead of the raw source files though.
