### ISSUE TITLE
evalmachine error

### ISSUE THREAD

**Issue by ORESoftware** [systemjs/builder#795]
ummm very confused here. I get this error:

```console
$ node my-builder.js 

evalmachine.<anonymous>:1
module.exports = {
^
ReferenceError: module is not defined
    at evalmachine.<anonymous>:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at Builder.executeConfigFile (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/builder.js:300:17)
    at Builder.loadConfigSync (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/builder.js:310:21)
    at new Builder (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/systemjs-builder/lib/builder.js:54:10)
    at Object.<anonymous> (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/systemjs-builder.js:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

my systemjs.conf.js file is like so:

```js
module.exports = {
  map: {
    'a': 'b.js'
  }
};
```

and the script that I ran which threw the error looks like:

```js
let path = require('path');
let Builder = require('systemjs-builder');
let builder = new Builder(__dirname, path.resolve(__dirname + '/systemjs.conf.js'));

builder
.bundle(path.resolve(__dirname + '/browser-polyfills/systemjs/all-core-and-npm.js'), 'dist/outfile.js')
.then(function() {
  console.log('Build complete');
})
.catch(function(err) {
  console.log('Build error');
  console.log(err);
});

```

no idea why module would not be defined

**Comment by ORESoftware** [comment]
oh no did you really want us to do this:

```
{
  map: {
    'a': 'b.js'
  }
}
```

instead of this?

```
module.exports = {
  map: {
    'a': 'b.js'
  }
};
```


that sir is bad because of this (syntax highlighting):

<img width="299" alt="screenshot 2017-04-04 18 47 58" src="https://cloud.githubusercontent.com/assets/11139560/24686228/53abd2c4-1967-11e7-861a-39e067b3f43c.png">

sad :(

**Comment by ORESoftware** [comment]
one thing is - it seems like this is running from the browser or something, I am so confused by this tool, sorrry just being honest

**Comment by guybedford** [comment]
SystemJS config files should be written:

```js
System.config({
  map: {
    a: 'b.js'
  }
});
```

This is because it is a browser resolution configuration file, so is designed to be loaded with a script tag, just like requirejs configuration.
