### ISSUE TITLE
SystemJS version in package.json should be ^0.20.*?

### ISSUE THREAD

**Issue by mikol-styra** [systemjs/builder#836]
@guybedford says in SystemJS issue https://github.com/systemjs/systemjs/issues/1613:

> SystemJS 0.20 uses the System.registry.get API, while 0.19 used System.get. If you're using SystemJS builder, make sure you're using version 0.16 for SystemJS 0.20, and version 0.15 for SystemJS 0.19.

But the required version in package.json is `"systemjs": "^0.19.46"`.

**Comment by mikol-styra** [comment]
Looks like JSPM is incompatible with a builder systemjs 0.20… `jspm bundle` (with JSPM 0.17.0-beta.47, systemjs-builder 0.16.12, and systemjs-builder using systemjs 0.20.19) errors out:

```
err  Error: Setting SystemJS.baseURL directly is no longer supported. Use SystemJS.config({ baseURL: ... }).
    at SystemJSLoader$1.set (/Users/mikol/src/com/styra/ui/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:3943:13)
    at Builder.reset (/Users/mikol/src/com/styra/ui/node_modules/systemjs-builder/lib/builder.js:140:41)
    at Builder (/Users/mikol/src/com/styra/ui/node_modules/systemjs-builder/lib/builder.js:45:8)
    at new Builder (/Users/mikol/src/com/styra/ui/node_modules/jspm/lib/bundle.js:45:19)
    at exports.bundle (/Users/mikol/src/com/styra/ui/node_modules/jspm/lib/bundle.js:185:23)
    at /Users/mikol/src/com/styra/ui/node_modules/jspm/cli.js:506:53
    at Object.<anonymous> (/Users/mikol/src/com/styra/ui/node_modules/jspm/cli.js:617:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Liftoff.<anonymous> (/Users/mikol/src/com/styra/ui/node_modules/jspm/jspm.js:40:5)
    at Liftoff.<anonymous> (/Users/mikol/src/com/styra/ui/node_modules/liftoff/index.js:202:12)
```

JSPM sets `SystemJS.baseURL` directly in a number of places even though it depends on SystemJS 0.20.19.

**Comment by guybedford** [comment]
SystemJS builder specifically still relies on SystemJS 0.19 due to some hooks dependencies unfortunately.
