### ISSUE TITLE
Overriding fetch hook causes exception

### ISSUE THREAD

**Issue by also** [systemjs/builder#97]
I'm trying to add a `fetch` hook as documented at https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader

It isn't clear from the documentation how to configure loader hooks using the builder, but looking at the source it looks like `builder.loader` is the right place.

I've installed systemjs-builder 0.9.1, and I have the file `build-test-fetch.js`:
```javascript
var Builder = require('systemjs-builder');

var builder = new Builder();

builder.loader.fetch = function(load) {
  return 'console.log("fetched", ' + JSON.stringify(load.address) + ')';
};

builder.build('myModule', 'outfile.js')
.then(function() {
  console.log('Build complete');
})
.catch(function(err) {
  console.log(err.stack ? err.stack : err);
});
```

When I try to build, I get an exception:
```
node build-test-fetch.js
Build error
TypeError: Error loading "myModule" at file:/Users/rberdeen/work/systemjs-test-fetch/myModule.js
Cannot read property 'myModule' of undefined
    at Loader.loader.instantiate (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:765:23)
    at Loader.loader.instantiate (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:940:30)
    at Loader.loader.instantiate (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1087:30)
    at Loader.loader.instantiate (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1172:30)
    at Loader.loader.instantiate (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1458:30)
    at Loader.loader.instantiate (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:1765:32)
    at Loader.loader.instantiate (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/compilers/amd.js:344:36)
    at /Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1547:31
    at tryCatchReject (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/Users/rberdeen/work/systemjs-test-fetch/node_modules/systemjs-builder/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
```

**Comment by guybedford** [comment]
SystemJS uses the fetch hook for certain state changes, so just overriding the fetch hook outright isn't supported.

Here's a hack that might work - 

```javascript
var systemLocate = System.locate;
System.locate = function(load) {
  return systemLocate.call(this, load).then(function(address) {
    // intercept the naming to give a new schema to file access
    address = 'newschema:' + address.substr(5);
  });
}

var systemFetch = System.fetch;
System.fetch = function(load) {
  return systemFetch.call(this, load).catch(function(e) {
    if (e.toString().substr(0, 14) == 'Only file URLs') {
      // didn't correspond to a `file:` URL, so handle alternative processing here
      return newFetchSource;
    }
  });
}
```

Will certainly put some thought to making this workflow easier in future.

**Comment by guybedford** [comment]
Would this perhaps be better solved by permitting URLs to be built?

**Comment by guybedford** [comment]
In concept, overriding the hooks / using a custom loader in the build can completely work, and we've also added an API via `builder.reset(customLoader)` so that one can actually provide a custom loader implementation to be used. This should cover these scenarios fine, provided the custom loaders are written as extensions in a backwards-compatible pattern.
